### ISSUE TITLE
largest-series-product forces implementation

### ISSUE THREAD

**Issue by markijbema** [exercism/xruby#10]
The tests for this exercise test a lot of the helper methods. I think given that it's this late in the path, it isn't needed. Also, it takes away a lot of freedom from the implementer. I think the tests should be guiding more by functionality needed than by methods defined.

**Comment by kotp** [comment]
Related information: 

* [largest series exercise test and soltuion](https://github.com/exercism/xruby/tree/master/largest-series-product)
* [Meta for exercise](https://github.com/exercism/x-common/blob/master/largest-series-product.yml)
* [Readme data](https://github.com/exercism/x-common/blob/master/largest-series-product.md)

Listed here for my convenience.

**Comment by kotp** [comment]
@markijbema and @kytrinyx hopefully this is what you had in mind.

**Comment by kotp** [comment]
BTW: in the spirit of "Look to exercism for awesome code" I took the following measurements:

```
Flogging your code!
    44.7: flog total
     5.6: flog/method average

    11.9: Series#separate                  example.rb:30
     7.1: Series#largest_product           example.rb:9
     6.7: Series#collection_of_digits      example.rb:36
     6.4: Series#analyzer                  example.rb:17
Your code reeks this much!
example.rb -- 2 warnings:
  [19]:Series#analyzer contains iterators nested 2 deep (NestedIterators)
  [26]:Series#reduce_to_product doesn't depend on instance state (UtilityFunction)
```

**Comment by kotp** [comment]
```
   42.6: flog total                                     
    4.3: flog/method average                            
                                                        
    6.7: Series#collection_of_digits      example.rb:45 
    6.5: Series#analyzer                  example.rb:22 
    6.4: Series#validate_length           example.rb:17 
    6.1: Series#separate                  example.rb:39 
```

**Comment by kytrinyx** [comment]
That's a much nicer result.
