### ISSUE TITLE
Wordy incorrect test

### ISSUE THREAD

**Issue by dalexj** [exercism/xruby#116]
I'm making this an issue because I'm not sure if this was intentional or not, but the `wordy_test.rb` has the test:

```ruby
def test_add_then_multiply
  question = 'What is -3 plus 7 multiplied by -2?'
  assert_equal(-8, WordProblem.new(question).answer)
end
```

my complaint is the following:

`-3 + 7 * -2 = -17`

`(-3 + 7) * -2 = -8`

if this was intentionally built this way, can something be put as a comment to the test, or in the readme?

otherwise change to `-17`?

**Comment by kytrinyx** [comment]
Huh, yeah, that's no good. Let's change the answer to -17.

**Comment by dalexj** [comment]
I'd love an explanation of this in the readme/test

**Comment by kytrinyx** [comment]
Yeah, it should probably go in the README. I'll start a discussion about it with the track maintainers first, since other people may have other thoughts about this.

**Comment by kotp** [comment]
Is this a spoken word problem or a written word problem?  The spoken word problem can be manipulated by pausing for an answer at the first operation, which provides the parenthesis which enforces order of operations.  If it is written, then it is up to the reader to apply the order of operations (PEMDAS) as is appropriate and expected.

**Comment by kytrinyx** [comment]
I see this as a spoken word problem.

**Comment by kotp** [comment]
Another bump, as the 'fix' is simple, but sometimes connecting with people is hard.

**Comment by kotp** [comment]
Should we ask forgiveness?

Update the readme/test comment, and if it is something that fundamentally
breaks the thinking, then there will be noise.

**Comment by kytrinyx** [comment]
The README has been updated to reflect this. If there's noise we can discuss further.

**Comment by kotp** [comment]
Thanks, wanted to submit it both ways.

**Comment by kytrinyx** [comment]
Ah, I missed that. I think of this as a word problem, so my bias made me think it was fixed :)

**Comment by kotp** [comment]
You said 'verbal' not wprd. O thought... ok, now we are both confused. :)  I submitted it both ways as in a test message for failure, but also the README solution.  Cover both bases.  I am pretty sure I communicated in both places that it was a verbal word problem.

**Comment by kytrinyx** [comment]
LOL. Yes. Verbal. I'm so sorry. My brain was not functioning very well.
