### ISSUE TITLE
Missing edge cases in Circular Buffer tests.

### ISSUE THREAD

**Issue by JulianAndrews** [exercism/xruby#123]
None of the tests for the Circular Buffer exercise use `write!` with a `nil` argument or on a buffer that isn't full. I'm assuming that in both cases `write!` should perform identically to `write`, but many simple implementations of `write!` are likely to get these cases wrong.

I'd be happy to add test cases to address those issues myself!

**Comment by kotp** [comment]
I would suggest doing exactly that.  The tests will express exactly what it is you found, is good exercise, and makes it really simple for @kytrinyx to approve or reject or comment.

But from the words, this seems like a great set of tests to add!
