### ISSUE TITLE
Crypto-square test incorrect

### ISSUE THREAD

**Issue by alexkalderimis** [exercism/xruby#125]
In clojure, haskell, et. al the expectation for `"Madness, and then illumination."` is `"msemo aanin dnin ndla etlt shui"`, but in ruby it is `'msemo aanin dninn dlaet ltshu i'`. This is due to the tests falsely expecting the result to not be a transposition of the input with spaces, but the flattened transposition separated into chunks the same size as the row length.

**Comment by alexkalderimis** [comment]
Also, the tests included the skips as `skip("Skip")` which the `Makefile` doesn't strip, so it seems that the example doesn't even pass the current broken tests - fixing now.

**Comment by kytrinyx** [comment]
Thanks for catching this. There has been a bit of confusing back-and-forth in the crypto square example.
