### ISSUE TITLE
Should the 'file not found' message in hamming be included in hello_world instead?

### ISSUE THREAD

**Issue by trayo** [exercism/xruby#130]
It seems like it will be more useful in hello_world rather than hamming.
Here is the error message:
```ruby
__END__

*****************************************************
You got an error, which is exactly as it should be.
This is the first step in the Test-Driven Development
(TDD) process.

The most important part of the error is

      cannot load such file

It's looking for a file named hamming.rb that doesn't
exist yet.

To fix the error, create an empty file named hamming.rb
in the same directory as the hamming_test.rb file.

Then run the test again.

For more guidance as you work on this exercise, see
GETTING_STARTED.md.
*****************************************************
```

**Comment by kotp** [comment]
Indeed, this used to be the first exercise, and so this should definitely be moved to the current 'first' exercise.  Can you do the honors?

**Comment by trayo** [comment]
@kotp Now that I look at it, should the [GETTING_STARTED.md](https://github.com/exercism/xruby/blob/master/hamming/GETTING_STARTED.md) and [example_gen.rb](https://github.com/exercism/xruby/blob/master/hamming/example_gen.rb) also move to hello_world?

I don't know exactly what `example_gen` does though.

**Comment by kotp** [comment]
That tool looks like it is something that is used for when all the system is put together.

**Comment by kytrinyx** [comment]
I'm going to be refactoring `example_gen.rb`. It is an experiment for generating the hamming test suite based on shared metadata. It should not go into the hello world problem.
