### ISSUE TITLE
Missing test for Binary?

### ISSUE THREAD

**Issue by bmulvihill** [exercism/xruby#135]
I noticed while working on this solution that the case where a binary string is only numbers, i.e. 123 isn't covered.  I noticed this while trying to determine if a string was valid I could pass the tests by doing something along the lines of:

```ruby
   def to_decimal
    return 0 if n.to_i == 0
    n.reverse.each_char.with_index.map { |char, index| char.to_i * 2**index }.reduce(:+)
  end
```

the test for string carrot123 returns 0, which is fine, but if i put 123 as a string my method would return a value,11 in this case.

**Comment by kytrinyx** [comment]
Nice, yepp. That seems like a missed test case.

**Comment by kotp** [comment]
@bmulvihill Do you have a test that covers this?  Would you be up for submitting a pull request?

**Comment by bmulvihill** [comment]
Sure I'll submit one in a bit!

**Comment by kotp** [comment]
:shipit:
