### ISSUE TITLE
Some files are skipping tests in Travis

### ISSUE THREAD

**Issue by kotp** [exercism/xruby#158]
`custom-set` and `ocr-numbers` both have tests that are being skipped in Travis

**Comment by kotp** [comment]
Currently these two problem sets, if the skips are disabled, fail.  Unsure why the example file does not address these tests, as I thought these were used as the aluminum standard<sup>[1](#aluminum_standard)</sup> and required for inclusion.

* * * *
<a name="aluminum_standard">1</a>: Aluminum Standard - In programming, the code which demonstrates an idea, perhaps given as an example of usage, but not up to the 'gold standard' which could be brought on by refactoring or redesign.

**Comment by kotp** [comment]
@kytrinyx When you review this, understand that if you pull these in, we will likely have some long standing Travis breakage reports... we should hold off until ocr-number is either suspended or corrected.

Contact the author for working `example.rb`?

**Comment by kytrinyx** [comment]
Yeah, I'd like to avoid having long-standing CI failures. I think I originally made ocr-number, but I bet the test suite has changed a few times over the past few years. I'll take a look.

**Comment by kytrinyx** [comment]
The problem with OCR is that someone's editor at some point removed trailing whitespace, which is crucial to actually solving the problem.

**Comment by kotp** [comment]
Thansk @kytrinyx everything is cleaned up and working well locally and with Travis.
