### ISSUE TITLE
Local checks not cleaning up their temporary files

### ISSUE THREAD

**Issue by kotp** [exercism/xruby#164]
This presumably happens on the Travis server as well, but may be automatically cleaned due to a reboot (just like on any Unix machine, if it honors traditional behavior).

However, like many traditional *nix machines, my machine can store many of these files, as the likelihood of a reboot happening for many days, perhaps many months, is slim.  We should be good citizens and remove the temporary files we create, as they are meant to be temporary.

**Comment by kytrinyx** [comment]
Yeah, good call. With travis they actually destroy the container after each run, I believe, so it's pretty ephemeral. But still: they could change that behavior at any time.
