### ISSUE TITLE
Distinguishing between quotations and contractions in Word Count

### ISSUE THREAD

**Issue by Calvyn82** [exercism/xruby#176]
The final spec test in Word Count looks for the use of apostrophes, which is a great idea that got me thinking.

The quiz could have one more test that included the use of apostrophes inside of contractions, but also had words in single quotes.

This would make for an interesting level of difficulty at the end of the quiz, requiring users to write something that checked how the punctuation was being used. If this seems like a good idea, I'm willing to write the pull request for it, but I didn't want to proceed unless it was something desired by others.

If creating a breaking test in a quiz that is in production isn't something that is acceptable, I understand.

**Comment by kytrinyx** [comment]
We've been very easy-going about breaking changes in the test suites. We've started introducing the idea of a [version constant for book-keeping purposes](https://github.com/exercism/xruby/blob/master/hamming/hamming_test.rb#L79-L84), which lets us avoid the "your code doesn't pass the test" discussion in the nitpicks.

I think the idea is interesting, and I'd be curious to hear what others think. @kotp -- thoughts?

One thing that we might notice is that if the exercise becomes more challenging, we may want to move it slightly further along in the track. I don't think that this change would [change the classification of the exercise](https://github.com/exercism/x-common/issues/63).

**Comment by kotp** [comment]
I would be interested in seeing at least a description of the test that is being considered here.   A pull request whether accepted, considered for a new exercise, or not accepted is no where near a waste of time, in my opinion.  It clarifies what the ideas are.

**Comment by kotp** [comment]
I am still trying to figure out how 'parenthesis' falls into this, from the title?  @Calvyn82 any ideas to show a working test?

**Comment by Calvyn82** [comment]
I'll write a pull request up when I get off tonight, but the test sting might be something like:

"Joe can't tell between 'large' and large."

Or

"He said, 'That isn't what he said.'"

**Comment by Calvyn82** [comment]
I see your confusion now. It's because I'm an idiot sometimes and I said parenthesis in the title when I meant quotations.

**Comment by kotp** [comment]
Fixed the title.

**Comment by kytrinyx** [comment]
Closed by #117
