### ISSUE TITLE
README for food-chain is way too vague

### ISSUE THREAD

**Issue by Rojo** [exercism/xruby#179]
Most persons are just loading the included `song.txt` file and returning its content to make the test pass. Is it the intended way to work the exercise or should people generate the song programatically?

If the later is the intended task, I think it should be stated clearly in the README and _test file_ for the exercise. Also, displaying a warning message when `File.open` or `IO.read` are used would be nice.

**Comment by kytrinyx** [comment]
Yeah, the idea was to generate the song programmatically. I think we should rethink the test-suite and also (as you suggest) take another look at improving the README.

**Comment by Rojo** [comment]
Addressed on https://github.com/exercism/xruby/pull/181 and https://github.com/exercism/xruby/pull/184.
