### ISSUE TITLE
Robot name's README and tests communicate different expectations about the code.

### ISSUE THREAD

**Issue by connorlay** [exercism/xruby#183]
Here's the description of `robot_name.rb` in the README:
~~~
Write a program that manages robot factory settings.

When robots come off the factory floor, they have no name.

The first time you boot them up, a random name is generated, such as
RX837 or BC811.

Every once in a while we need to reset a robot to its factory settings,
which means that their name gets wiped. The next time you ask, it gets a
new name.

Random names means a risk of collisions. In some exercism language
tracks there are tests to ensure that the same name is never used twice.
~~~

Based on the README, `#name` should act as a command the first time it is called, then act as a query each consecutive call. Robots should be initialized with no name. Yet in the tests you see this:
~~~ruby
COMMAND_QUERY = <<-MSG
    Command/Query Separation:
    Query methods should generally not change object state.
  MSG

...

  def test_name_sticks
    robot = Robot.new
    robot.name
    assert_equal robot.name, robot.name
  end

...

  def test_reset_name
    robot = Robot.new
    name = robot.name
    robot.reset
    name2 = robot.name
    assert name != name2
    assert_equal name2, robot.name, COMMAND_QUERY
    assert_match NAME_REGEXP, name2
  end
~~~
Is `#name` a command or a query? `test_name_sticks` suggests `#name` is a command, yet in `test_reset_name` it looks like a query. `COMMAND_QUERY` indicates there should be a separation, yet the README disagrees.

Since there is no test for robots initialized without a name, it is not clear which interpretation is correct.

**Comment by kotp** [comment]
You skip over the `test_has_name` which does test that a Robot that is new, when asked for a name, has a name generated that matches the pattern.  The name method then acts as a generator. (I think this is what you mean by a 'command'.)  By generating something, it then at the same time also acts as a query.

What is checked for, is that, and as you show in your snippet above, is that the query function is also tested, as state is not changed when we call `name` on our Robot.

**Comment by connorlay** [comment]
This is the part I found confusing:

`Query methods should generally not change object state.`

There is an assertion message that encourages the separation of query and command methods. A robot's API, according to the tests, consists of `#name` and `#reset`. `#reset` is definitely a command, as it always changes the robot's state. `#name` is a command the first time it is called (changing a new robot's name from `nil` to something like `AB123`) and a query for all future calls.

I guess my main concern is this exercise seems to discuss the idea of command/query separation, yet the implementation of `#name` encouraged by the README combines the query and generation of a robot's name into one method. I don't think it matters much (especially since `#name` is lazily evaluating a robot's name and functions like a query from an outside perspective) but the inclusion of the assertion message threw me off.

I know this is nitpicky but I was genuinely curious about the goal for this exercise.

**Comment by kotp** [comment]
Oh no, you didn't just nitpicking nitpick a nitpicking nitpickers nitpicking source code, did you? :8ball: 

If you do have a test that can help clarify, yet not drive the implementation (too much) I would like to see it.  

You did bring my attention to another point as well, though.  The mention that a new robot won't have a name, yet we don't really test for that.  Looking at the way to check for this, I can't find a way that won't specifically require a certain instance variable by name, and no others.

**Comment by kotp** [comment]
@kytrinyx  can you [look at this](http://exercism.io/submissions/fbe0ec16b59043c8abd72b14eaf65590)?  there is obviously an issue with this, as the name apparently gets set in the initialize method, but I think that is against the description and intention.  (Though not tested for.)

**Comment by kytrinyx** [comment]
When I created the exercise, I didn't intend it to specify that name should be both a query and an exercise, only that there is a reset mechanism.

If the only way to find out a Robot's name is to ask it for the name, and having done so, the Robot gets a name, then there is no difference whether the name gets generated at setup time, or whether it's generated the first time a name is called.

I will clarify the README.

**Comment by kytrinyx** [comment]
Actually, the README is fine. It says:

> The first time you boot them up, a random name is generated

That suggest that it happens during setup, but it doesn't have to. It doesn't sound to me like this means that it happens when you ask a Robot for its name.

**Comment by kytrinyx** [comment]
Fixed in https://github.com/exercism/x-common/commit/eb6c1ec415f42b0753c2bba9cf7687933c15b68f
