### ISSUE TITLE
Failing Tests in Gigasecond

### ISSUE THREAD

**Issue by kickinbahk** [exercism/xruby#186]
I am not sure if I am missing something, but I think I have the problem solved correctly and the test is failing. Looking at what it is expecting back, the test seems it is expecting a date that it is much further in the future than it should be.

This is the test that is failing, it is passing in a date in 2011, and expecting a date in 2043. 

```
12  def test_2011_04_25                                                                                                                                                       
13    gs = Gigasecond.from(Time.utc(2011, 4, 25, 0, 0, 0))                                                                                                                    
14    assert_equal Time.utc(2043, 1, 1, 1, 46, 40), gs                                                                                                                        
15  end  
```

Here is the code that I have written: 

```
def self.from(time_start)                                                                                                                                                  
    time_start += (10**9)/(60*60*24)                                                                                                                                         
end    
 ```

While I know that this can be written better, in the spirit of the red green refactor, I was trying to just get it to pass at this point, which it should.

This is the error that I am getting from minitest: 

```
Finished in 0.002493s, 2807.3091 runs/s, 802.0883 assertions/s.

  1) Failure:
GigasecondTest#test_2011_04_25 [gigasecond_test.rb:14]:
Expected: 2043-01-01 01:46:40 UTC
  Actual: 2011-04-25 03:12:54 UTC

7 runs, 2 assertions, 1 failures, 0 errors, 5 skips 
```

**Comment by kytrinyx** [comment]
A gigasecond is 31.7 or so years, so 2043 seems correct.

When you have a date object in Ruby and add 1, you add a day, but when you have a Time object and add one you add a second. Could that be what's confusing things?

**Comment by kickinbahk** [comment]
thanks @kytrinyx I will look into this further then.
