### ISSUE TITLE
VERSION constant - how can we clarify this?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xruby#188]
Someone incremented the `VERSION` number in their Hamming solution so that iteration 1 had `VERSION=1`, and iteration 2 had `VERSION=2`.

The current test says:

```
  # This test is for the sake of people providing feedback, so they
  # know which version of the exercise you are solving.
  #
  # Define a constant named VERSION inside of Hamming.
  # If you're curious, read more about constants on RubyDoc:
  # http://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/constants.html
```

Could we come up with a better explanation that clarifies that they should not change the test, and that the version is not about the solution, but about the test suite?

Should we name the constant something else?

**Comment by kotp** [comment]
The version number in the solution should match the (exercise authors) version number in the test suite that you are solving for.

**Comment by kotp** [comment]
I suppose if we generated the program file that they are editing, then this could automatically be included.  And that would automatically match the test version, if it is there.  Solve it in a technical way, having a note to indicate that it should only be changed if they have read 'whatever'.

**Comment by kytrinyx** [comment]
Even if we generate the program file, there's still the possible confusion about incrementing the `VERSION` in their subsequent iterations. Maybe if we just say "Do not edit this test. For more about this read XYZ."

**Comment by kotp** [comment]
Something that communicates it is for track maintainers only.  But they are welcome to maintain the track too.

Maybe "This number usually doesn't need to change.  Edit the test only to modify the "skip" portions -- See "How to update the track tests.""

**Comment by kotp** [comment]
But if we generate that file initially, it can have the information you want in there, the hint about what the version number is there for.  I would be careful to not drive anything that makes their decision of a module or class though, or something other.

**Comment by kytrinyx** [comment]
Right, but we can also put the information in the test. That's the piece that we don't want people to change (if they don't change it in the test, they can't change it in the solution).

**Comment by kotp** [comment]
True..  Then it comes down to the track maintainers being informed to do so.

This is very likely system wide update?  Not sure how many language tracks have the multiple tests implemented.

**Comment by kytrinyx** [comment]
At the moment I would settle for just fixing it in Ruby. I think that it has been used in Go as well, but I haven't seen any evidence that gophers are confused by it.

**Comment by sguermond** [comment]
"Problems in exercism evolve over time as we find better ways to ask questions. The version number refers to the version of the problem you solved, not your solution."

**Comment by kytrinyx** [comment]
I like it, @sguermond!

**Comment by kotp** [comment]
Perfect...

**Comment by kickinbahk** [comment]
Hey guys, I would love to help with adding this and adding the version tests to the ruby track at least. However Travis keeps rejecting the PR. If someone is willing to help me understand what I am missing I will love to help!

**Comment by kytrinyx** [comment]
Absolutely! I'll check out travis' complaints now.

**Comment by kytrinyx** [comment]
OK, it looks like it's passing now, but it mixes a couple different types of changes (a missing skip, and the VERSION comment for accumulate and rna-transcription).

It's a lot easier to pull things in if each PR is very focused.

Here's the list of all the exercises that have a version constant in Ruby:

- [ ] word-count
- [ ] twelve-days
- [ ] rna-transcription
- [ ] gigasecond
- [ ] food-chain
- [ ] binary
- [ ] acronym
- [ ] hamming (**Note** this one has a generator, so it's a bit more complicated to fix it)
