### ISSUE TITLE
Test Framework

### ISSUE THREAD

**Issue by mikeyjcat** [exercism/xruby#214]
What was the reason for choosing minitest over rspec?

**Comment by kytrinyx** [comment]
It's simpler, and there's no magic.

**Comment by mikeyjcat** [comment]
Magic?

**Comment by kytrinyx** [comment]
"magic" as in with RSpec it actually takes a pretty solid understanding of Ruby to understand how it works. Minitest is much more straight forward.

**Comment by mikeyjcat** [comment]
OK, thanks
