### ISSUE TITLE
Difference of squares and formatting

### ISSUE THREAD

**Issue by mikeyjcat** [exercism/xruby#215]
In the test suite, we've got a couple of long integer values e.g. 25_164_150. I'm busy with the test generator, and the shortest way to generate these correctly would be to use a regex to create the correctly formatted string. Are you happy with this approach?

**Comment by kytrinyx** [comment]
Yeah, that seems totally fine.

**Comment by mikeyjcat** [comment]
Thanks. The next one submitted needed this.
