### ISSUE TITLE
Transcription doesn't go both ways... only DNA to RNA

### ISSUE THREAD

**Issue by mhelmetag** [exercism/xruby#231]
This is part of a larger [issue] (https://github.com/exercism/x-common/issues/148) to remove RNA to DNA "transcription" from the `rna-transcription` exercise across all languages.

Files to edit are [here](https://github.com/exercism/xruby/tree/master/rna-transcription).

**Comment by kytrinyx** [comment]
+1 - thanks for this.

**Comment by mhelmetag** [comment]
Yay! One down.
