### ISSUE TITLE
question re: guard and file naming conventions

### ISSUE THREAD

**Issue by neurogenesis** [exercism/xruby#237]
Examples up to "nth_prime" have used file names that match the test name (minus "^test_"). This makes it easy to use tools like Guard to monitor the entire exersicm ruby path and execute tests only for files where source or tests have changed (like when removing skips for example). This makes it a lot easier to continually get instant test feedback.

Out of curiosity, do all exercises adhere to this naming convention? If so, I will try and cobble together a Guardfile that can be used for all exercism/ruby challenges.

**Comment by kytrinyx** [comment]
Yes, the naming convention is: _`:name`.rb_ for the production file, and _`:name`_test.rb_ for the test file, where `:name` is derived from the directory that the exercise is in (replacing hyphen with underscore).

```
solution_file = "#{slug.gsub('-', '_')}.rb"
test_file = "#{slug.gsub('-', '_')}_test.rb"
```

**Comment by neurogenesis** [comment]
Excellent. Thanks!
