### ISSUE TITLE
Spelling/grammar fixes

### ISSUE THREAD

**Issue by GoobleJook** [exercism/xruby#238]
Yeah, I'm that guy. Sorry. ;-)

"Ruby is simple in appearance, but is very complex inside, just like our human body1."
 -- unnecessary "1" at end.

"You can read more about the Ruby language on it's site."
 -- "...its site".

**Comment by kytrinyx** [comment]
Thanks @GoobleJook! I love getting these fixed.

**Comment by kytrinyx** [comment]
Deploying the fix now.
