### ISSUE TITLE
simple-linked-list: overload Nil#nil? or have non-nil class return true for nil?

### ISSUE THREAD

**Issue by copiousfreetime** [exercism/xruby#249]
There are two tests that cause solutions to this problem, to have, what I think, is non-idiomatic ruby.

* https://github.com/exercism/xruby/blob/master/exercises/simple-linked-list/simple_linked_list_test.rb#L45 requires that the object returned from `Element.from_a` return `true` for `#nil?`
* https://github.com/exercism/xruby/blob/master/exercises/simple-linked-list/simple_linked_list_test.rb#L71 requires that the object returned in the previous bullet point respond to `#reverse`

There are two solutions to this:
* add `Nil#reverse` which is altering a core class of ruby, which I'm not really a fan of. Yes you could do this with refinements, but I'm not a fan of that solution either
* Create a `NullElement` or other similar `NullObject` pattern that returns `true` for `#nil?` which I consider bad form also.

The latter is the solution that the example program uses (https://github.com/exercism/xruby/blob/master/exercises/simple-linked-list/example.rb#L63-L65) and I think this is bad form in ruby because:

```
null_element = NullElement.new
puts "null element is #{null_element.nil? ? "nil" : "not nil"}"
puts "null element is #{null_element ? "truthy" : "falsy" }"
# => null element is nil
# => null element is truthy
```
And that output is just wrong.

How should we fix this?

**Comment by kotp** [comment]
Do you have an idea of what you would present as a solution to your concerns?  A PR would do wonders.  I need to make one for "dead code" that I found in this exercise.

**Comment by copiousfreetime** [comment]
Yup, I'll work up a PR. Just wanted to see if there was agreement that this was a valid issue before working on it.

**Comment by kytrinyx** [comment]
> add Nil#reverse which is altering a core class of ruby

eew, let's not do that :)

> Create a NullElement or other similar NullObject pattern that returns true for #nil? 

eew! No, that seems like a terrible idea. Only instances of NilClass should return true for #nil?

Totally agree that we should fix the problem.

**Comment by neontapir** [comment]
Thanks, @copiousfreetime!
