### ISSUE TITLE
broken help link in SETUP.md

### ISSUE THREAD

**Issue by behrtam** [exercism/xruby#253]
The help pages got moved as a result the link (http://help.exercism.io/getting-started-with-ruby.html) in the [SETUP.md](https://github.com/exercism/xruby/blob/master/SETUP.md) (which is included in the generated README for every exercise) is broken. I guess the new link is: http://exercism.io/languages/ruby

**Comment by kotp** [comment]
Are you up for doing a pull request for this to fix this?
