### ISSUE TITLE
Leap kata assertions

### ISSUE THREAD

**Issue by renemaya** [exercism/xruby#256]
Hi, as I started solving the Leap kata and rather than un-skip the tests from top to bottom I wanted to solve the test for 1996, 2000 and 1900 (in that order). To my surprise an empty string makes the first two assertions pass. I looked into [Minitest documentation](http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Assertions.html) and noticed that:

> [...] assert [...] Fails unless test is truthy.

Since we are already checking against a string, perhaps it would be better to use assert_equal? If you agree with that I could do a pull request with those changes

**Comment by kytrinyx** [comment]
Leap is testing against a string? It's testing against a boolean, as far as I can tell.

**Comment by kotp** [comment]
Remember that a string, empty or otherwise, is truthy.  The key word then is that it fails unless it is 'truthy'.

**Comment by renemaya** [comment]
:flushed: I see... still lots to learn. Thanks for the hint @kytrinyx (and exercism in general) and further explanation @kotp

**Comment by kytrinyx** [comment]
Please do feel free to ask questions if you get confused! Always happy to help clarify.
