### ISSUE TITLE
Inconsistencies in the Circular Buffer exercise

### ISSUE THREAD

**Issue by neontapir** [exercism/xruby#257]
In this exercise, `write!` forces a value in the buffer to be overridden. This behavior is reinforced by `test_overwriting_oldest_item_in_a_full_buffer`. However, this leads to what I believe is a test error in `test_forced_writes_of_nil_should_not_occupy_buffer`.

The beginning of the `test_forced_writes_of_nil_should_not_occupy_buffer ` test reads as follows (`circular_buffer_test.rb` lines 92-96, with the resulting buffer contents in the comments):

    buffer = CircularBuffer.new(2)  # [nil, nil]
    ('1'..'2').each { |i| buffer.write i }  # [1, 2]
    buffer.write! nil  # [nil, 2], I believe                  
    assert_equal '1', buffer.read  # test failure, 1 != nil
    assert_equal '2', buffer.read

The only way for both of these asserts to pass would be for the `buffer.write! nil` call to have no effect and leave the buffer as `[1, 2]`. However, previous tests of `write` with `nil` show that it should clear the value of that location. Therefore, I believe the two tests mentioned above are in conflict with one another.

**Comment by kytrinyx** [comment]
Yeah, I think you're right that forcing a write of `nil` should behave the same way in both cases.

My first thought is to suggest that if you're forcing something, including nil, it should take whatever you give it.

**Comment by petertseng** [comment]
Well, first I'll say that I think this is incorrect:

> However, previous tests of `write` with `nil` show that it should clear the value of that location.

The tests currently read

```ruby
  def test_writes_of_nil_should_not_occupy_buffer
    buffer = CircularBuffer.new(5)
    buffer.write nil
    ('1'..'3').each { |i| buffer.write i }
    assert_equal '1', buffer.read
  end

  def test_forced_writes_of_nil_should_not_occupy_buffer
    buffer = CircularBuffer.new(2)
    ('1'..'2').each { |i| buffer.write i }
    buffer.write! nil
    assert_equal '1', buffer.read
    assert_equal '2', buffer.read
    assert_raises(CircularBuffer::BufferEmptyException) { buffer.read }
  end
```

In both cases, it is expected that the write (whether that be a `write` or a `write!`) of `nil` will have no effect. In the `write` case, if the `write(nil)` had an effect, the first value read out would be `nil`. In the `write!` case, if the `write!(nil)` had an effect, also the first value read out would be `nil`.

So the tests are consistent with each other.

It might still be worth discussing whether writing `nil` should in fact have no effect, but if that change is to be made, both tests mentioned above will need to change, not just one.

**Comment by kytrinyx** [comment]
I don't know what the original thinking was with the nil. On the one hand it seems really odd that we would make `nil` have no effect, but also not raise an error. This is kind of weird and unexpected behavior.

**Comment by kotp** [comment]
Considering common use of a circular buffer, it seems that adding (or attempting to add) 'nil' would be a "no op" , rather than an error state.  It seems to make sense to me.  Given the reading material and the support of the surrounding tests, it doesn't seem to be an error in testing.

**Comment by kytrinyx** [comment]
@kotp Is this referenced in reading material that we point to in the README? (I'm recovering from a combination of brutal travel and illness, and haven't looked at what we reference yet--I could do so once I catch up with all the issues on GitHub).

**Comment by kotp** [comment]
I see that there is a link to [Wikipedia's Circular Buffer](http://en.wikipedia.org/wiki/Circular_buffer) article  My reference to 'common use' is simply the keyboard buffer that most everyone uses.

**Comment by kytrinyx** [comment]
How do you input a nil into a keyboard buffer? (I'm feeling a bit dumb here--I suppose I use the keyboard buffer, but I've never thought about it)

**Comment by kotp** [comment]
Kind of the point, you would not... and it doesn't make sense to, and you shouldn't.  Circular buffer, the nil (or empty slot in a fixed amount of slots) gets there when the read happens and there is nothing else to go on the buffer.

**Comment by kytrinyx** [comment]
To me it doesn't sound like the case of the keyboard buffer makes an example either way with regards to nil. I could see the argument that there are no nils, and so a hypothetical nil would be a no-op, but I could also see the argument that there are no nils, and so a nil would be a very weird error state.

**Comment by kotp** [comment]
You are right, the keyboard is just a well known example, not really an argument to behavior toward nil.

I realize now that my statements about nil is a big red :fish: (read "herring") in that I am focusing on the nil and its interpreted meaning, rather than just the fact that it is something on a circular buffer.  The README seems to me to be very clear.  Something in, something out, in a FIFO manner.  Nothing about normalizing data, nothing about nil being some kind of special thing, nothing stating that it has to be numbers, even though numbers are used to make the example simple and concise.

Removal should result in an empty location, until something else is read.  Full buffer needs to communicate that nothing can be written, with the exception of a forced write.  If they want to write clowns in the positions, then clowns it can be.  If those clowns happen to be nil, so be it.  As long as those positions are the oldest (LI) for the write, then it follows the description of the README to a "T".

I can only speculate that someone was trying to not allow a forced write of nil to the locations in an attempt to "flush" the buffer.

**Comment by kytrinyx** [comment]
> If they want to write clowns in the positions, then clowns it can be. If those clowns happen to be nil, so be it.

Yeah, this is where I'm leaning as well.

> To be clear... I think the tests for nil are likely candidates for removal, they are too restrictive for the perceived intent, as I read the code. Nil should be allowed as long as it is allowed as any other object in the buffer, and removed as any other object in the buffer.

Yes, this sounds like a good approach.
