### ISSUE TITLE
Should sieve come before nth-prime?

### ISSUE THREAD

**Issue by Aqualon** [exercism/xruby#258]
Solving the nth-prime task involves some kind of Prime-number generator, which has to be implemented in the sieve exercise at a later point. Wouldn't it make sense to first give sieve to users and then let them find out in nth-prime how to use the sieve to solve it?

**Comment by kytrinyx** [comment]
Sure. There are other ways than `sieve` to write a prime number generator, but you make a great argument.

**Comment by kotp** [comment]
Let's finish talking about this, and let someone get this in place.

I say we can move sieve to happen before nth-prime.  Perhaps between pangram and roman-numerals.

That will leave a couple of exercises between sieve and nth-prime, and break them up between "mathy" exercises.

To patch this is simple.  The hard part is figuring out the best place to put it.  So it is perfect for first-timers-only.  If someone needs help with this, it won't be with "coding" just with the process of contributions.

So what is needed to do now is simply OK the placement... and let someone grab this and do it.

**Comment by kytrinyx** [comment]
I agree we should have a break between "mathy" exercises (same as with "lots-of-text-y" exercises).

I think somewhere between pangram and roman numerals sounds good.

**Comment by kotp** [comment]
OK, so I think this is now set up to be an awesome first patch for someone!  It isn't high priority, and it is easy to do, and it has the idea of how to do this in this set of comments...

Who wants it? :balloon:

**Comment by mostlybadfly** [comment]
Hello all, I'd love to do this.  I see that config.json seems to have the order of the exercises, is the best place to make the change?  I'll take a look in a couple of hours when I'm on lunch and can use my laptop :)

**Comment by kotp** [comment]
@mostlybadfly great to see you here!

If you do have any questions don't hesitate to ask.  

I think you did find the place to make the change.

**Comment by mostlybadfly** [comment]
@kotp thanks! submitted the PR.  Is there a list of all issues I can go through to find some beginner friendly ones? Or is it best to just peruse all the repos in the organization?

**Comment by petertseng** [comment]
@mostlybadfly Ah, it sounds like you are looking for something organisation-wide? I can help out with that: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Aexercism+label%3A%22good+first+patch%22

(Hmm @kytrinyx  should we throw a link to this search query somewhere where people can see?)

Note that this depends on the track maintainers having marked issues as good first patch, which it's not certain all tracks have done, so if you don't find anything that interests you from the list you could check a specific repo you are interested in and see if they have any issues they haven't gotten to labeling yet. But I feel like the above list could be a good start.

**Comment by kytrinyx** [comment]
That search is definitely one good place to start. Another is to go to the [x-common issues](https://github.com/exercism/x-common/issues) and [filter on the "cross-track consistency" label](https://github.com/exercism/x-common/issues?q=is%3Aissue+is%3Aopen+label%3A%22cross-track+consistency%22). It has a BUNCH of things that are very well-defined and would make great first/early patches.

Look at some of the issues, and scroll down so you can see the linked issues. Let us know if you have questions, we're actively trying to improve the process!

(@petertseng, yeah we probably should. README of the exercism.io website, maybe? Not really sure. Maybe we should open a discussion in the discussions repo about coordinating this sort of thing better).

**Comment by mostlybadfly** [comment]
Wow thanks all, you are wonderful.  Exercism is a great tool and I'm looking forward to contribute!

**Comment by kotp** [comment]
Looks like everything is good here, closing the issue!
