### ISSUE TITLE
Incorrect test in Largest Series Product exercise

### ISSUE THREAD

**Issue by neontapir** [exercism/xruby#262]
In `largest_series_product_test.rb`, line 18:
```
def test_can_find_the_largest_product_of_2
  # skip
  assert_equal 48, Series.new('576802143').largest_product(2)
end
```

The only pair of numbers that would yield a product of 48 in this string are 6 * 8, but 6 and 8 are not consecutive. The largest product of consecutive numbers is 7 * 6 = 42, so the test should expect 42.

**Comment by neontapir** [comment]
The next test `est_finds_the_largest_product_if_span_equals_length` does not obey the consecutive number constraint as well. Perhaps the README is in error and not the tests.

**Comment by neontapir** [comment]
I think it is my interpretation of the word consecutive that is the issue here. I think the author meant adjacent in the sequence (for '134', pairs '13' and '34' are consecutive), whereas I thought it meant adjacent in the set of integer numbers (for '134', only the pair '34' is consecutive). This confusion could be eliminated by using an example in the README that differentiates between the two.

**Comment by petertseng** [comment]
Seems like the same confusion as in #244 . Both these exercises could do with a clarification as to what "consecutive" means (by position, not by numeric value). An issue should be opened in x-common to address this.

**Comment by kotp** [comment]
You will open suggested issue @peterseng ?

**Comment by petertseng** [comment]
For various reasons I can't file at the moment so I would prefer if @neontapir would file

**Comment by kytrinyx** [comment]
I've filed it here: https://github.com/exercism/x-common/issues/197
