### ISSUE TITLE
binary: improve tests for invalid numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xruby#275]
We should have separate tests for:

- alphabetic characters at the beginning of a valid binary number
- alphabetic characters at the end of a valid binary number
- alphabetic characters in the middle of an otherwise valid binary number
- invalid digits (e.g. 2)

If the test suite for binary has test cases that cover these edge cases, this issue can safely be closed.

See https://github.com/exercism/x-common/issues/95

**Comment by kotp** [comment]
I like the suggestion about common test data, but I will look into this more later today as well.

**Comment by kotp** [comment]
@kytrinyx I think this is one that would be perfect for first patch or first timers only.  I know that we are thinking about x-common tests for this, but that could be some time, in the meanwhile this could be put in place.

**Comment by casto101** [comment]
I'm a first time open source contributor! I'd love to tackle this.
