### ISSUE TITLE
Gemfile.lock

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/xruby#280]
It seems odd to neither have it on the .gitignore nor in the repo.
Apologies if this has been discussed, but I did a quick search and turned up nothing.

**Comment by kotp** [comment]
Thanks for bringing this to our attention.

I will check the history and see if this was discussed.

Since this is not a gem, perhaps it is something we should consider tracking.

Which way do you think it should go?

**Comment by kotp** [comment]
I put it in the ignore for right now.  I am not solidly sold on it yet though.

This repository isn't deployed, it is only under development, and it isn't a gem.... It is driving me toward ignoring it.

It gets generated with Travis and when the `bin/local-status-check` executable is ran during development.

@kytrinyx what do you think? @kytrinyx ?

**Comment by kytrinyx** [comment]
I don't have a strong preference either way, but I lean towards ignoring the lockfile since the dependencies are only needed for development (we've put the version of minitest in the require for the actual test suites so that people don't try to run it with 4.x).

**Comment by Cohen-Carlisle** [comment]
Sounds reasonable. :+1:

**Comment by kotp** [comment]
Thanks @Cohen-Carlisle and @kytrinyx
