### ISSUE TITLE
Add Versions

### ISSUE THREAD

**Issue by callahat** [exercism/xruby#290]
Some examples and test suites do not have version numbers. If an exercise does not yet have a version, its version should be added. The `VERSION` should be added to example.rb, and a test should be added to the corresponding *_test.rb file if it does not already have one.

(As per the following comment, unversioned examples are assumed to be version 0: https://github.com/exercism/xruby/pull/277#issuecomment-209079078)

**Comment by kotp** [comment]
This is an ongoing thing as exercises are converted to generated exercises.  No need to open a "master" issue here.

Feel free to work on making them generated though, if there is a test set in x-common repository, it is prime.
