### ISSUE TITLE
Exercism Nitpickers POV - Remove skips?

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/xruby#297]
I personally find the `skip`s a bit annoying as they need to be removed over and over.
I understand the idea is not to overwhelm the user with errors... it seems like a nice idea but gets old after a while.
If I only want to work on one case, I can just solve the first failure and rerun!
A middle ground could be to have them on the first `n` exercises and not after that.
Thoughts?

**Comment by kotp** [comment]
They don't need to be removed at all.  See the [README](https://github.com/exercism/xruby/blob/master/README.md) in the root.  Also linked here for convenience.

**Comment by Cohen-Carlisle** [comment]
I'm speaking more from the POV of a consumer of the exercism CLI client.
I think its ultimately a distraction (moreso than multiple failing tests) to the primary focus of exercisms... learning to code/a new language/write super-clean code.

**Comment by kotp** [comment]
When the failures come in no particular order, how does that work to assist an orderly and progressive solution?  The tests will be ran in no particular order when you do comment them out.

This means that you need to know the testing tool so that you can specify which test to run, which feature you are working on... that is not a bad thing to know... for sure.

**Comment by Cohen-Carlisle** [comment]
I didn't realize that minitest shuffles the order of your tests.
That certainly complicates things. Of course, we could also override this.

**Comment by kotp** [comment]
I would prefer not to use the method that is required to do such a thing, we want to get better than that. :sweat_smile: but I would be for educating folks on how to use minitest to only test the one thing that they need, or a category of things that they need.

In the short run, especially if they are just learning their tools, the editor they use; the testing framework, and the language, yes, it makes things a little bit, well, just, 'more'.

In the long run, you learn your tools and flourish, or you don't and continue to feel like things are getting in your way.  I prefer to give that feeling of freedom.

It starts somewhere, it may as well start with us.

I am happy to see some documentation improvements, I think @kytrinyx is looking forward to this as well.

I do need to update the documentation on that side for running pretty tests and showing test names.  Adding a section on how to run a single test or a subset of tests may be helpful there.  We will see.

**Comment by kytrinyx** [comment]
I did write the hack for running tests in the order that they were defined a couple years ago: https://github.com/kytrinyx/minitest-homework

There is a way to get a consistent order in minitest (`i_suck_and_my_tests_are_order_dependent!`) but that runs them in alphabetical order, and I also don't want to tell people that they (or we) suck. The context here is different.

I would be all for figuring out how to help people figure out how to fix this for themselves (write hacks, create aliases, etc).

**Comment by Cohen-Carlisle** [comment]
I'm kind of coming around to the idea that skips are the least evil way to deal with the test shuffling. I think explicitly stating this in the documentation would be a good thing. Right now, referencing skips, it just says: `This is so that you don't have to deal with all the failures at once.`

**Comment by kytrinyx** [comment]
That's a great point. We should explain the thing about the order being shuffled, and that the skips help with that as well as the all at once thing... and maybe we could point to the "disable skips" script we have in this repo and suggest that they do something similar if they don't want to deal with skips.

**Comment by kotp** [comment]
The changes will end up at http://exercism.io/languages/ruby but should we also have this information downloaded in the README that is in the exercise folders @kytrinyx, when we fetch them?

This means changing `./SETUP.md`in root.

**Comment by kytrinyx** [comment]
I was thinking... shouldn't the `TESTS` stuff just get included directly in the README? We should discuss this over in x-common first so all the track maintainers can weigh in, but I think it makes sense to put the "how to run the tests" instructions in all the exercises directly.

**Comment by kotp** [comment]
I was kind of thinking so as well.  Though the README in the exercise does defer to the website.

**Comment by kytrinyx** [comment]
Yeah, we might not need the stuff in SETUP if we include the TESTS.md, but we could also have the SETUP stuff. I'll open up the question in x-common.

**Comment by kotp** [comment]
Alright.  I was surprised this was merged in.  I have one change regarding the short version -n, rather than --name since some folks may use the nyan-cat reporter.

**Comment by kytrinyx** [comment]
LOL. I have never even seen the nyan-cat reporter. That sounds kind of awful :)

Sorry I didn't mean to merge too quickly. I should have said LGTM and let you or @Cohen-Carlisle merge after a second pair of eyes were on it.

**Comment by kotp** [comment]
I was thinking about recording my terminal and sending you the text-cast style thing to watch. It is just a 'for-giggles' type of thing but really does stay out of the way.

Playing with a "How to customize your Gemfile for personal niceties" thing in a shared project while staying out of the way of the actual requirements.  Things that may be OS based, but not necessary for the actual program/project.

**Comment by kotp** [comment]
Peek at the branch that is now recreated (I did not notice that you deleted it, so it is sitting there.)
