### ISSUE TITLE
grade-school tests force one type of solution?

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/xruby#299]
The tests are calling to_h on the user defined class `School`, which heavily suggests using a hash.

I think thinking through how to structure the metadata might help us develop an API into `School` that is more agnostic of the underlying implementation.

Plus, x-common needs metadata for that, so 2 :bird:, 1 :moyai:.

**Comment by kytrinyx** [comment]
I'd love to see this improved to not guide people to a specific solution.

**Comment by Insti** [comment]
#375 is currently a 1 :bird: 1 :moyai: solution which covers the test portion but not the metadata yet.

`students_by_grade` still returns a hash as that seemed like the most sensible data structure to return.

The [Readme](https://github.com/exercism/x-common/blob/411222fe3202860b8866e4d6ae465e1810a5643d/grade-school.md) seems to suggest a more literal style which would return strings, I'm not sure if the output should be changed to match that. (My preference would be to return proper data structures that something else could use to create the strings.)

**Comment by Insti** [comment]
See also: #389, #390

**Comment by Cohen-Carlisle** [comment]
Closing this as referenced PRs have solved this.
