### ISSUE TITLE
food_chain not failing on use of File.read or IO.read

### ISSUE THREAD

**Issue by kotp** [exercism/xruby#300]
Tests call for it, and the tests are passing, but I am seeing solutions again that use File.read to solve food_chain lession.

**Comment by kytrinyx** [comment]
Do they have the most recent version of the test suite? If so, have you asked if they changed the test suite in any way?

**Comment by Cohen-Carlisle** [comment]
Just tried using `File::read` and got the expected error. I suspect they simply modified the tests to be able to pass or submitted it without running the tests.

The first example I came across of someone doing this also had `VERSION` set to `1` in their solution, while the current `VERSION` is `2`. The monkey patch that raises errors for file operations was not present for their version.

**Comment by kotp** [comment]
OK, I think you probably found the same one, as it was recent.  I also commented (pretty sure) on it to them.

**Comment by kotp** [comment]
@kytrinyx Waiting on a response from them, I believe.

**Comment by kotp** [comment]
@Cohen-Carlisle I found the reason that it passes in their current version.  The testing does fail if they use File.read in their method.  But, if they read the song.txt using File.read outside of their method definitions, the name spacing does not include those changes.  And so it is not restricted.

Pull request should be #301

**Comment by kytrinyx** [comment]
That's a great find!

**Comment by kotp** [comment]
This is still open, (well, because no one closed it) and I am thinking about how or if there is a mechanism for the "version" number to reliably actually indicate which set of tests are being used.  It has been a while since I have seen (only a week) someone change the version based on their iteration or some other impetus.

Any ideas?  Of course, this may just be something that happens anyway, as this is not something that we control, fully.  Perhaps the .version file should be relied on more heavily.

**Comment by kytrinyx** [comment]
> Perhaps the .version file should be relied on more heavily.

I'm not sure what you mean. Would you elaborate, please?

**Comment by kotp** [comment]
I think it may be that I have not noticed how the `.version` file is being used.

But I want to know with some confidence what tests are being ran against the solution, and the version setting in the exercise submission may not be reliable, since students change it sometimes.

**Comment by kotp** [comment]
The `.version` data is generated in the `generator.rb` file, which is why the confusion of not finding it in exercises where they have been modified to change the solutions, but not generated.

It is clearer now.
