### ISSUE TITLE
Trinary has been changed and has a backward incompatible test.

### ISSUE THREAD

**Issue by kotp** [exercism/xruby#308]
We should probably solve this by writing the generator for it, which will introduce VERSION to it naturally.

**Comment by Insti** [comment]
Trinary is being deprecated in favour of the new "all-your-base" exercise.
https://github.com/exercism/x-common/issues/279

I suggest we wait until that is implemented which will make this issue redundant.

**Comment by kotp** [comment]
closed because:  exercism/xruby#394
