### ISSUE TITLE
Solution Provided in Ruby Gigasecond Exercise

### ISSUE THREAD

**Issue by sono123** [exercism/xruby#315]
Maybe I'm doing something incorrectly, but when I enter "exercism fetch ruby gigasecond" in the command line client, the solution exists in gigasecond.rb and all the tests pass from gigasecond_test.rb?

**Comment by kotp** [comment]
checking...

**Comment by kotp** [comment]
Can you show what gigasecond_test.rb looks like?

**Comment by kytrinyx** [comment]
This is what is delivered:

```
~/exercism/ruby $ tree gigasecond/
gigasecond/
├── README.md
└── gigasecond_test.rb

0 directories, 2 files
```

**Comment by kotp** [comment]
That is what I thought.  When I ask for a solution specifically, it gets put in a 'solutions' folder.

So surprised that @sono123 reports that he gets a pre-done solution.

**Comment by sono123** [comment]
Just to clarify, was "exercism fetch ruby gigasecond" the appropriate CLI command? If so, that is all I pasted in (as per the instructions on the exercism.io). After running that command, voila... there was the file gigasecond.rb along with the solution in it. None of the other 3 exercises that I've done so far had this issue.

**Comment by kotp** [comment]
Here is what I found... 

```plain
[ruby] ll gigasecond                                                                                                                                                      20:52:09 
total 8.0K
-rw-r--r-- 1 george george 1.6K May  6 23:06 gigasecond_test.rb
-rw-r--r-- 1 george george 1.2K May  6 23:06 README.md
[ruby] exercism fetch ruby gigasecond                                                                                                                                     20:52:24 

unchanged: 1, updated: 0, new: 0

[ruby] l gigasecond                                                                                                                                                       20:52:34 
total 20K
drwxr-xr-x  2 george george 4.0K May  6 23:06 .
drwxr-xr-x 35 george george 4.0K May  6 23:06 ..
-rw-r--r--  1 george george 1.6K May  6 23:06 gigasecond_test.rb
-rw-r--r--  1 george george 1.2K May  6 23:06 README.md
-rw-r--r--  1 george george    1 May  6 23:06 .version
```

**Comment by kotp** [comment]
Sorry, to show the entire result... I reset it by deleting my folder and then issuing the command...

```plain
[ruby] rm -rf gigasecond                                                         20:58:07 
[ruby] exercism fetch ruby gigasecond                                            20:58:21 

New:              1 problem
ruby (Gigasecond) /home/george/exercism/ruby/gigasecond

unchanged: 0, updated: 0, new: 1

[ruby] ll gigasecond                                                             20:58:29 
total 8.0K
-rw-r--r-- 1 george george 1.6K May  8 20:58 gigasecond_test.rb
-rw-r--r-- 1 george george 1.2K May  8 20:58 README.md
[ruby]
```

**Comment by kytrinyx** [comment]
@sono123 What is the output of `exercism debug`? What happens if you rename the gigasecond directory and then fetch it again with `exercism fetch ruby gigasecond`?

**Comment by kotp** [comment]
Another report of this happening here: http://exercism.io/submissions/6b2c6caad4ac4b3a8a95a32a9ce97487

**Comment by kytrinyx** [comment]
This is so strange. I can't imagine what is happening with this. `fetch` just pulls together files that are on disk and serves them, filtering out `/example/i`.

**Comment by kotp** [comment]
I also got a report today that on Linux the client introduces indentation, but not on Mac... I had given feedback, they told me to ignore it as it wasn't coming from them. (I do suspect an editor setting though, that may be unobserved.)

But I am on the looking out for things like that as well.

**Comment by kotp** [comment]
Filtering out the example, yes... that is what I figured, so I was looking in the repositories for solutions in the exercises, perhaps forgotten, or missed in a pull request.  Apparently more and more of the solutions are getting inserted... Which it has been noted as well isn't even the 'example' code.

**Comment by kytrinyx** [comment]
so... we've added solutions by accident?

**Comment by kotp** [comment]
Somewhere, some how... and they are apparently being named appropriately, ie, gigasecond.rb apparently.

I just did a fetch and received only the run-length-encoding test and readme but not the solution...

I can not confirm it myself yet.

**Comment by kytrinyx** [comment]
What. The. Heck. I think the Makefile renames solutions, but it does so in a temporary directory. We aren't committing that back to the repo.

**Comment by tejasbubane** [comment]
Are there reports of this bug from languages other than `ruby`? Or is this happening just for `xruby` track?

**Comment by kotp** [comment]
So far I have only seen it for ruby, but I don't track the others as closely.

**Comment by kotp** [comment]
The fix is just around the corner!  Bug found, [swatter taken out](exercism/exercism.io#2882... and...

**Comment by kytrinyx** [comment]
deploying!

**Comment by kytrinyx** [comment]
Thanks everyone for reporting it. This one was super, super tricky!
