### ISSUE TITLE
Alternatives for the test constants?

### ISSUE THREAD

**Issue by remcopeereboom** [exercism/xruby#316]
At the moment all (most?) ruby tests include a test to ask for the ruby version. These tests require a constant scoped to the class under test. Here's a reminder from `acronym_test.rb`:

````ruby
  # Problems in exercism evolve over time,
  # as we find better ways to ask questions.
  # The version number refers to the version of the problem you solved,
  # not your solution.
  #
  # Define a constant named VERSION inside of Acronym.
  # If you are curious, read more about constants on RubyDoc:
  # http://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/constants.html
  def test_version
    assert_equal 1, Acronym::VERSION
  end
````

 [@kotp has pointed out that this prevents people from implementing certain solutions.](http://exercism.io/submissions/4d49fb77225f420fa444dbb4d9a6afc1) It has also bothered me that the name is `VERSION`, not something like `TESTS_VERSION` and that the constant does not really belong in the classes under test.

The easiest solution is to put the constants under `Kernel` (e.g. `Kernel::ACRONYM_TESTS_VERSION`) as you can avoid the specific scoping. This is easy for people to understand, easy to implement, and solves the problem @kotp mentioned.

Does anyone have any objects or better ideas?

**Comment by kytrinyx** [comment]
Thanks for kicking off this discussion. I agree that the current book-keeping is pretty dirty, and I would welcome an approach that solves the problem of helping reviewers understand that the solution was made against an older version of the tests, without constraining solutions.

I like the `Kernel::ACRONYM_TESTS_VERSION` suggestion. It's explicit and keeps out of the way.

**Comment by kotp** [comment]
@kytrinyx [This is an example](http://exercism.io/submissions/0731a634ef024fb499eda4f32e148f01) of what is possible in regards to Gigaseconds due to the test not over-specifying.  The strange thing, though, is that the 'This Looks Great' (not that it necessarily does) button is not there... I just noticed it today.

**Comment by kytrinyx** [comment]
The looks great button will show up on other people's solutions, not on your own.

**Comment by kotp** [comment]
Thanks, it made me feel nervous not seeing it there, greyed out or something...

**Comment by Cohen-Carlisle** [comment]
@remcopeereboom :+1:

**Comment by Insti** [comment]
Does the version indicator need to be a testable thing?

* There's no server-side solution checking so we don't really care which version of the tests was used.
* It only exists to aid discussion of solutions.
* From my own experience writing reviews I can tell which version of the tests someone has used by just looking at the solution.
* The current module based implementation adds unnecessary complication and verbosity to solutions.

Can we just suggest that people add a version comment to their solution?

```ruby
# Based on tests VERSION 2
```

**Comment by kytrinyx** [comment]
> Does the version indicator need to be a testable thing?

Not really. All of your points are true. The main problem we were trying to solve is that people come in and do reviews and say **you're wrong**, because the person didn't solve against the same test suite that they did. This is unnecessarily unpleasant. It doesn't happen super often, but even a little bit of this is not OK, to my mind.

A comment would work, but my experience suggests that unless there's a test forcing them to do it, they're going to ignore our suggestion.

**Comment by kotp** [comment]
I don't think that it must be testable, but the tests will remind them to do so.  And the module should be alleviating some unnecessary restrictions, before forcing a inclusion of something that did not belong in their module or class.

I was getting feedback that it was hinting that the solutions needed to be either a module or a class.  When many of the solutions don't need to be either a module nor a class, but can be something else altogether.

**Comment by kotp** [comment]
Closing since we are moving from class test version to book keeping test version.
