### ISSUE TITLE
Bug on sample dataset for Ruby problem: hamming

### ISSUE THREAD

**Issue by wwchen** [exercism/xruby#32]
I hope this is the right forum to submit bug reports on the sample dataset

First off, I am getting a warning:
```
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /Users/wchen/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/minitest/autorun.rb:15:in `<top (required)>'
  hamming_test.rb:1:in `<main>'
MiniTest::Unit.autorun is now Minitest.autorun. From /Users/wchen/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/minitest/autorun.rb:19:in `<top (required)>'
MiniTest::Unit::TestCase is now Minitest::Test. From hamming_test.rb:4:in `<main>'
```
**Warning message was suppressed by adding `gem "minitest"` to my `hamming_test.rb`**

Second,
I believe this test has an incorrect assertion:
```
  def test_ignores_extra_length_on_other_strand_when_longer
    assert_equal 2, Hamming.compute('AGG', 'AAAACTGACCCACCCCAGG')
  end
```
Correct me if I'm wrong, but assertion should be equal to **zero**:
```
AAAACTGACCCACCCCAGG
                AGG
```

**Comment by kotp** [comment]
The timing is right for this, as we are working on the hamming exercise.  Work through a solution and/or close?

**Comment by kytrinyx** [comment]
The hamming part of this has been fixed (it now raises an error).

The larger question applies to all of the problems: should we explicitly require that Minitest be installed as a gem? Is it still shipped as part of Ruby, and if so, what version?

I'm leaning towards explicitly adding `gem 'minitest', '~> 5.0'` or something similar to the problems and then making people install minitest, if it will reduce the friction/confusion around this.

**Comment by kotp** [comment]
This could be managed by using 'Bundler` and having a `Gemfile` in the exercises.  Unsure if that is the best way to go for this project, but it is now almost the 'defacto' for Ruby projects.

**Comment by kytrinyx** [comment]
If you don't have bundler, then this would be `gem install bundler && bundle install`, whereas if we just told you `gem install minitest` that would be simpler and less indirection.

**Comment by kotp** [comment]
Do we have a script that runs when you first install the exercism gem?  (In other words, it could be a dependency of the gem.)  A rake test task that looks at your current working directory, and tuns the required test.  The infrastructure is already here, I think.

**Comment by kytrinyx** [comment]
There's no exercism gem--just the binary which has no other dependencies. A rake task would be nice, but I don't think the infrastructure is in place, unless I'm thinking about this all wrong.

**Comment by kotp** [comment]
Strange.  As I have this gem installed:

`exercism (0.0.28)`

Investigating it now.

**Comment by kotp** [comment]
Yeah... and the dependencies include both minitest and bundler...

    spec.add_development_dependency "bundler", "~> 1.3"
    spec.add_development_dependency "minitest", '~> 5.0'

**Comment by kotp** [comment]
Exercism gem has been deprecated... :) never mnd.

**Comment by kotp** [comment]
This should be closed if all there is to do is notify folks to install the gem.  The instruction is in the hello/-world/GETTING_STARTED.md file to do the `gem install minitest` which I think is sufficient.

And this does leave the 'set up an automated testing workflow' environment as a learning exercise for individual study as needed.

**Comment by kotp** [comment]
You mentioned about explicitly requiring a minimum version of Minitest?  I think the new name for Minitest::Test does this automatically/naturally, to the extent that the syntax doesn't exist in an older version.

**Comment by kytrinyx** [comment]
> You mentioned about explicitly requiring a minimum version of Minitest?

Yeah, if people are using a version of Rails that requires minitest 4.x, then it becomes pretty complicated to get this to run without warnings.

I think adding `gem install minitest` to the instructions, and specifying `gem 'minitest', '~>5.0'` at the top of the exercise file will ensure that it runs clean.

**Comment by kotp** [comment]
Your comment has me shaving yaks this afternoon and evening.  Still investigating implications.  I use Bundler, so trying to simulate what people do who use neither a version manager of some kind, to include Bundler.

**Comment by kytrinyx** [comment]
I hope those yaks didn't ruin your day!

**Comment by kotp** [comment]
Closing this issue as this is a "Two part" thing and the second part really has nothing to do with the hamming problem.  Creating a new issue to track "explicitly require that Minitest be installed as a gem".
