### ISSUE TITLE
Sublist

### ISSUE THREAD

**Issue by steve21168** [exercism/xruby#335]
Liana and Steve working on sublist

**Comment by bernardoamc** [comment]
Since we have a PR open for this problem, should we still keep this issue open?

**Comment by lianaluci** [comment]
We just finished writing an example, we'll close the issue now!

**Comment by kytrinyx** [comment]
One common way of handling this is to put `Closes #335` in the title or message of the pull request, or in one of the commits that make up part of the pull request. That way when the PR gets merged, this issue would get closed automatically.

**Comment by kotp** [comment]
7pm (Eastern Time, as in New York) tonight we have a pair programming session planned, it will cover things like this, setting up niceties in a template file, and some other things.

Anyone is welcome to join, just message me, @kotp on twitter or my e-mail on github is fine as well. (Chat works there, as far as I can tell.)

**Comment by Insti** [comment]
This is currently in progress as #427

**Comment by kotp** [comment]
@insti fighting with @probot-stale[bot] ?
