### ISSUE TITLE
Adding Bank Account

### ISSUE THREAD

**Issue by angyangie** [exercism/xruby#336]

**Comment by bernardoamc** [comment]
Since we have a PR open for this problem, should we still keep this issue open?

**Comment by angyangie** [comment]
Hey,

Thanks for contacting me about this issue. This is actually the first open
source contribution I make on the web, so I'm not sure what I'm doing yet.
Could you tell me what your pull request title is so I can look it up?

I actually just finished coding a solution/test file for this and would
love to upload it if possible!

Thanks,
Angie

**Comment by angyangie** [comment]
I'd love any suggestions/comments you may have on the process! I'm
currently learning how to code and know I could use all the help I can get.

Thank you again,
Angie

**Comment by bernardoamc** [comment]
Sure @angyangie! I think we can close this issue and keep working or your open pull request.  What do you think?

**Comment by angyangie** [comment]
Thanks so much, yes, I now realize what you meant. We can close the issue!

**Comment by bernardoamc** [comment]
When your pull request is ready for review, just add a message like "Ready for review" in it and I will take a look. :)
