### ISSUE TITLE
nth-prime test suite throwing error ThreadError:deadlock; recursive locking

### ISSUE THREAD

**Issue by rebelwarrior** [exercism/xruby#352]
The following line in the Test suite causes the error down below. 
In particular it is the re-writing of the `:new` method that is causing the problem:

```{ruby}
class Prime
  [:each, :new, :prime?, :take].each do |m|
    define_method(m) { |*_| fail ERROR_MESSAGE }
  end
end
```

```
  1) Error:
TestPrimes#test_first:
ThreadError: deadlock; recursive locking
    /Users/davidacevedo/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
    /Users/davidacevedo/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:140:in `instance'
    /Users/davidacevedo/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:142:in `block in instance'
    /Users/davidacevedo/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
    /Users/davidacevedo/.rbenv/versions/2.3.0/lib/ruby/2.3.0/singleton.rb:140:in `instance'
    nth_prime_test.rb:30:in `test_first'
```

**Comment by bernardoamc** [comment]
Thanks for reporting @rebelwarrior !

After investigating the error I found that there is an open [issue](https://bugs.ruby-lang.org/issues/11953) in `bugs.ruby-lang` regarding this, and the report is reproduced using exactly this exercise. Not sure what to do yet, going to think about it.

**Comment by Cohen-Carlisle** [comment]
In my opinion, there is very little value in trying to stop "cheating" this way. The exercist is really only cheating themselves. I favor removal of the anti cheat as impacting a non cheating user is worse than not catching a cheating user.

**Comment by bernardoamc** [comment]
> In my opinion, there is very little value in trying to stop "cheating" this way. The exercist is really only cheating themselves. I favor removal of the anti cheat as impacting a non cheating user is worse than not catching a cheating user.

Agreed, seems like the best approach.

**Comment by rebelwarrior** [comment]
Ha! that's funny I found a JavaScript/Elm bug the same way with an exercism test. 

I also recommend removing the anti cheating device. 

- David.

**Comment by kytrinyx** [comment]
+100, let's do it.
