### ISSUE TITLE
Discussion: Refactoring exercises?

### ISSUE THREAD

**Issue by devonestes** [exercism/xruby#361]
I listened to @kytrinyx on the Bike Shed this week, and I loved the idea of refactoring exercises. I've been thinking of a couple ways in which that could be, done, but I wanted to bring it up here to get more feedback, and also to see if there is interest in having some refactoring exercises in the Ruby track.

So, my first thought is that we'd have an entirely new exercise, but this one would already be making all the tests pass. Then the user would be able to refactor the code as much as they like in an attempt to make it better while still keeping the tests green. For example, I can write a pretty poorly factored Markdown parser or something like that, and then let people go nuts making it better.

I don't think it would make sense to have a previously existing exercise for a refactoring exercise because then the user would have a reference in their heads already about how to refactor it. It would be better (I think) to have them come to the given problem totally fresh (unless they've written a Markdown parser before).

So, what do you think?

**Comment by kytrinyx** [comment]
Would you mind posting this to the discussions repository? https://github.com/exercism/discussions This affects all the tracks.

**Comment by kytrinyx** [comment]
_Notes to self: Once we have an issue about refactoring exercises, transfer interesting thoughts and snippets from https://github.com/exercism/x-common/issues/94 to it. Also: we have a refactoring exercise called "ledger"._

**Comment by devonestes** [comment]
@kytrinyx Done!

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/24
