### ISSUE TITLE
Leap: No test failure messages.

### ISSUE THREAD

**Issue by Insti** [exercism/xruby#366]
When tests fail they give no indication of why they failed.

All the failure message strings are set to ''

Best solution: Add informative failure messages.

Easiest solution: Remove the empty strings so it at least gives the message that there is a failure with no message.

**Comment by Insti** [comment]
@kotp it seems that this commit: 65cc1259de8d6ecba969eb14d1bf388f5e6479d7 blew away all the failure messages.

**Comment by kytrinyx** [comment]
Aaah, very well spotted. Thanks!

**Comment by kotp** [comment]
Thanks for catching that, @Insti I did miss that.  That's what we get for not testing our tests.
