### ISSUE TITLE
Gemfile does not specify Ruby version

### ISSUE THREAD

**Issue by kotp** [exercism/xruby#371]
The current version of Ruby for the website is Ruby 2.2.2, should we expect the code to work on a minimum version of Ruby and if so, should we "enforce" this via the `Gemfile`? 

The benefit:

* Better information from Rubocop
* A good place for exercise designers to know what to design and test against

**Comment by Cohen-Carlisle** [comment]
If we include something like this, I think we should do it like this:
```
raise 'Ruby version must be at least 2.1' unless  RUBY_VERSION.to_f >= 2.1
```
and support any Ruby that has not reached end of life.

**Comment by kytrinyx** [comment]
Enforcing this is a bit overkill, to my mind. If older versions of Ruby work, then fine. We could put something in the README to say that we are not explicitly supporting any Ruby versions that have reached end of life.

**Comment by kotp** [comment]
I see, nice placement of 'not' there. :+1: .

What versions of Ruby are we using while maintaining this track?  I find that I am often using Ruby 2.3.1.

**Comment by Insti** [comment]
2.1.5 or 2.2.2 depending on which machine I'm on.

**Comment by kotp** [comment]
It is already being enforced with the Travis CI, though at version 2.1.2,  I want a way to have the local checks use that information as well.  I ran into where the documentation states I can indicate a minimum, but that is where I hit the snag.  

Tests, ran at the CI level, to help decide if a push will pass Travis, before we get the late notification.  Right now, that doesn't necessarily happen, even if you run the local status check tool.

**Comment by Cohen-Carlisle** [comment]
Should we close this issue along with #372, @kotp?
