### ISSUE TITLE
alphametics `test_solve_puzzle_with_multiplication` has 6 solutions

### ISSUE THREAD

**Issue by dalexj** [exercism/xruby#376]
this test is asking for one specific solution when there are many. I have no idea how to handle this or what to change because this exercise seems extremely ambiguous. would love to just bring up some discussion

**Comment by Insti** [comment]
Can you post the test and the solutions you have found?

**Comment by kotp** [comment]
Can you show some code here to help explain?  Or a link for ease of reference?  Here is what I am looking at in regards to this issue:

https://github.com/exercism/xruby/blob/master/exercises/alphametics/alphametics_test.rb#L28

What are the 6 solutions?  Why do you think 6 is not enough or more than enough solutions?  How should the solutions be restricted or expanded?

**Comment by dalexj** [comment]
all these answers work for this test:

```ruby
Alphametics.new.solve('IF * DR == DORI')

{"I"=>8, "F"=>2, "D"=>1, "R"=>4, "O"=>1}
{"I"=>8, "F"=>2, "D"=>3, "R"=>9, "O"=>1} # this one is the answer in the current test
{"I"=>8, "F"=>8, "D"=>3, "R"=>6, "O"=>1}
{"I"=>9, "F"=>1, "D"=>8, "R"=>9, "O"=>0}
{"I"=>9, "F"=>3, "D"=>2, "R"=>3, "O"=>1}
{"I"=>9, "F"=>9, "D"=>8, "R"=>1, "O"=>0}
```

**Comment by Insti** [comment]
Your extra solutions have repeated digits.

Each letter should represent a different digit, and the leading digit of a multi-digit number must not be zero.

I've created an [issue on x-common](https://github.com/exercism/x-common/issues/273) to add this information to the README

**Comment by dalexj** [comment]
gotcha, that makes much more sense now. I'll close this issue
