### ISSUE TITLE
Remove rubocop magic comments from user facing files

### ISSUE THREAD

**Issue by Cohen-Carlisle** [exercism/xruby#385]
We have magic comments disabling Rubocop metrics in some of the test files.
Rubocop is an internal tool and not anything that an exercist should have to concern themselves with.
Having it show up in the test file is noisy and potentially confusing.

**Comment by kotp** [comment]
Potentially confusing yes, but the churn in `.rubocop.yml`, do you think it will increase the number of conflicts for merging?  I think that is a very confusing thing for new contributors.

Having it in the test files says "Hey, we know that you may have read the best practice is to have x, but in this case, we are ignoring it."

@kytrinyx what do you think? 

Also, I do think that the goal is to have 100% no Rubocop comments, they are a nuisance, and indicate some kind of "something" that is not "accepted style".  But then, I think that is a good goal regardless of if it is user facing or hidden in the `.rubocop.yml` file.

**Comment by Insti** [comment]
Anecdata: I run Rubocop on all my files when doing Exercism problems, so removing Rubocop magic comments would cause me to need to add them in again locally.
(My usage is certainly atypical)

**Comment by kytrinyx** [comment]
I personally find rubocop to be more of a bother than a help. I generally disagree with a lot of the defaults. I think that we should choose a small handful of rules that we actually believe are important to be consistent with and stick to them, and disable everything else at the project level.

**Comment by kotp** [comment]
Then I think the next step is:

* Which files get checked
* What is "important"

**Comment by kytrinyx** [comment]
My suggestions:

- two spaces for indentation
- always include parentheses for method definitions or message sends when there is at least one argument
- no trailing whitespace (only because it adds noise to diffs that I'd rather avoid)

I'd also be open to something that specifies that arrays/hashes are either one-liners (if short enough) or like this:

```
[
  "a",
  "b",
  "c",
]

{
  "a" => "aye",
  "b" => "bee",
  "c" => "cee",
}
```

And not:

```
[ "a",
  "b",
  "c",
]


{ "a" => "aye",
  "b" => "bee",
  "c" => "cee",
}
```

**Comment by kotp** [comment]
Yeah, I like the trailing commas myself, as well.  Rubocop (read Github team) really doesn't like them.  We love the github team.

I don't know if you are including the trailing comma in the same way I am taking it though.

I agree the delimiter should be on its own line when it is multi-line.

What about leading dot or trailing dot for multi-line chained method calls?

```ruby
collection.
  sort.
  reverse
```

vs

```ruby
collection
  .sort
  .reverse
```

I prefer the latter.

**Comment by Insti** [comment]
I'd argue that multi-line chained method calls are a worse smell themselves so it doesn't matter.

**Comment by kytrinyx** [comment]
> multi-line chained method calls are a worse smell themselves

I find that if they're all operating on the same type, I generally don't find them smelly.

> I don't know if you are including the trailing comma in the same way I am taking it though.

Oh, right. Yeah, I try to always keep them in, but that's the same as with trailing whitespace. Not having them tends to add more noise in changes. I don't feel strongly about them, though.

**Comment by Insti** [comment]
With the new (extremely permissive) Rubocop philosophy #443 in action, these disabling comments are now redundant and can be safely removed.

If you want to find them, try this command: `grep -rl 'rubocop:disable' exercises`
(There are currently 26 files.)

Simply remove any `rubocop:disable` or `rubocop:enable` comments:
```ruby
  def test_discard_arrays # rubocop:disable Metrics/MethodLength
```
becomes
```ruby
  def test_discard_arrays
```
