### ISSUE TITLE
Stale Pull Requests

### ISSUE THREAD

**Issue by bernardoamc** [exercism/xruby#393]
What is the current policy to deal with stale pull requests?

If we look at the list of open PRs we can see that the majority was opened from May 13 to May 17 ( they were part of a workshop if I'm not mistaken). Most of them have not been updated and I'm afraid this could reduce/be reducing the number of new PRs, first because these exercises are literally blocked and second because some people generally avoid contributing to projects with tons of open PRs.

**Comment by kotp** [comment]
I don't know of any "Policy" but they should be bumped and then if no response from the owner, and it is a good PR, then ownership can be assumed.

**Comment by bernardoamc** [comment]
Maybe policy is the wrong word here? :)

But thanks for the info, I'm going to close this.

**Comment by kytrinyx** [comment]
> What is the current policy to deal with stale pull requests?

I've asked this question in the general discussions: https://github.com/exercism/discussions/issues/56
