### ISSUE TITLE
Move food-chain exercise to later?

### ISSUE THREAD

**Issue by c1505** [exercism/xruby#399]
I noticed that about half of the people that complete couple solutions before food-chain do not complete food-chain.  I was wondering if it would be better to move that exercise to later in the order.

**Comment by kotp** [comment]
I think Beer song is at least on appearance simpler than this one.  Perhaps they should be swapped?

**Comment by Insti** [comment]
Food-chain should definitely be moved to later. Although it might not be particularly difficult it's still a lot of work to solve. I think it should be moved *much* further down the list.

Anecdata: I stopped the fetch next/do/submit cycle when I got to food chain because it seemed like a lot of work and not something I could just do quickly.
Caveat: I had coincidentally just watched [Katrina's "Succession" talk](https://www.youtube.com/watch?v=59YClXmkCVM) so my estimation of what was required might have been off.

**Comment by c1505** [comment]
@kotp Yea my counts are just from what is visible when you see the problems you have completed on the ruby track.  The dropoff looks worse than it probably really is because of the re-ordering that was done here https://github.com/exercism/xruby/commit/fb93c66b7a5b9ccaef89c434377dd7523d4eff95 .  

Just looking at what was completed after that, it seems to go from about 700 to about 400.  This is just estimates from clicking around from what I can see as a user.

Remembering my own subjective experience of the problem, I was not happy with my solution at the time and ended up just making it pass and moving on because it didn't feel like I could get to a well factored solution with my level of understanding at the time.  After seeing Katrina's talk, I will go back and take another stab at it soon.

**Comment by kotp** [comment]
That is definitely an option, but not one that is stated in the documentation.  If there is something that is hard, that you may not be ready for, I don't consider it inappropriate to submit even a non-working example, open up discussions, and go from there.

Maybe the option should be proposed and presented formally.

With the upcoming `--all` open on the cli tool, this is likely to happen more often, as if you decide to grab all of the exercises, then order is pretty much (and is currently somewhat already) arbitrary, and has less of an effect on that person.

Of course, for those that chose to do the non-working submission, the numbers as you observe them in this way become less meaningful, as it indicates that it has been worked on (not necessarily solved.)

**Comment by c1505** [comment]
@kotp not sure what you meant here 
"That is definitely an option, but not one that is stated in the documentation.".  

I agree that it isn't clear that we can submit non-working solutions.  Only realized that a few exercises in when I was wondering how someone's code worked, pasted it in my editor and realized it didn't.  A FAQ page might be good or some better onboarding.  

Getting back to the order of the exercises, where do you guys think food-chain would be best moved to?  Are you still thinking swap with beer-song @kotp ?  All I know is that I think it should be after where I am in the exercises (phone-number), but I haven't done the later ones so I don't have a good idea of where it should fit in.  Do you have a placement suggestion @Insti ?

**Comment by kotp** [comment]
I think it might be good here, but would be up for a change in order.  I don't have a strong opinion.

Since @insti thinks it should "definitely" be moved, I would guess he has a better idea than I do.  I don't have a strong feeling either way, nor position.

**Comment by Insti** [comment]
I'll submit a PR with an updated position sometime when I get a chance over the next few days.

**Comment by Insti** [comment]
Food chain had now been moved further down the order.

Old: 
```
      "bob",
      "food-chain",
      "run-length-encoding",
```
New:
```      
    "bracket-push",
    "food-chain",
    "matrix",
```

It will be interesting to see if this makes a difference.
"run-length-encoding" has 105 solutions right now.

**Comment by Insti** [comment]
Thanks to @c1505 for encouraging us to look into this.
