### ISSUE TITLE
Wordy tests violates precedence rules of arithmetic

### ISSUE THREAD

**Issue by srabuini** [exercism/xruby#415]
Hey!

I think that https://github.com/exercism/xruby/blob/master/exercises/wordy/wordy_test.rb#L71-L75 is wrong according to the precedence rules of arithmetic.

Or maybe I'm not understanding something.

Thanks!

**Comment by Insti** [comment]
You are correct that it is wrong according to the precedence rules of arithmetic, but the Readme for the problem says: 
> Remember, that these are verbal word problems, not treated as you normally would treat a written problem. This means that you calculate as you move forward each step. In other words, you should ignore order of operations. 3 + 2 * 3 = 15, not 9.

**Comment by srabuini** [comment]
My bad. Sorry about that! It's 3:56 am here.

**Comment by Insti** [comment]
No problem, Maybe you could submit a PR to the test file that gave a more helpful test failure error message in that case.
