### ISSUE TITLE
Queen-Attack missing test cases

### ISSUE THREAD

**Issue by remcopeereboom** [exercism/xruby#439]
This might be a duplicate of #396, but queen attack is missing test cases for testing that queens are actually placed on the board. These test cases _are_ in the [x-common tests](https://github.com/exercism/x-common/blob/master/exercises/queen-attack/canonical-data.json).

**Comment by Insti** [comment]
Thanks. We should still have correct test cases even if they are manually generated.

What needs to happen:

Either 
a) Write a generator 
OR
b) Manually fix the [queen_attack_test.rb](https://github.com/exercism/xruby/blob/master/exercises/queen-attack/queen_attack_test.rb) file.

**Comment by remcopeereboom** [comment]
I'll see if I can submit a fix to the .rb file later today.

I'm not familiar with the protocol for the generators. I'll have a look at the alphametrics one to figure out what the desired design is. I could probably write one for `queen_attack`.

**Comment by Insti** [comment]
Manually adding the missing cases is fine.
