### ISSUE TITLE
Poker test suite

### ISSUE THREAD

**Issue by moveson** [exercism/xruby#446]
The poker exercise test suite should include at least one test that includes a '10' card to test the integrity of the rank/suit parser.

One of the tests is called `test_an_ace_high_straight`. It is actually testing a five-high straight. The name should be changed to avoid confusion.

There should be a test of a five-high straight against another straight. The five-high straight is the lowest possible straight, and it constitutes a special case in which the ace ranks lower than a 2 both for purposes of determining if the straight exists (which is already tested) and for scoring purposes (which is not currently tested).

There should also be a test comparing high-card hands that are identical except for the last card, to ensure the scoring algorithm is complete.

I have written tests for these cases; they can be found [here](http://exercism.io/submissions/56200d8c069b4786be1e2ec3b8bdbeb1).

**Comment by kotp** [comment]
Are you comfortable creating a pull request for this?

**Comment by moveson** [comment]
Yes, I can do that.

**Comment by moveson** [comment]
Can you give me permission to create a new branch?

**Comment by Insti** [comment]
@moveson You need to fork the repository then create a new branch on your fork.

**Comment by kotp** [comment]
#450 is the PR for this issue.
