### ISSUE TITLE
Common generator interface

### ISSUE THREAD

**Issue by bmulvihill** [exercism/xruby#452]
While working on a generator I noticed most exercise generators ({exercise-name}_cases.rb) have a different method names for the same purpose. For example the test values, some generators call this method assertion, others call it do, or work_load.  The same goes for the test naming and skip methods.  This can lead to some confusion and also code duplication.

I think a common interface would go a long way towards reducing some code duplication and making it easier to create new generators.

**Comment by Insti** [comment]
I'd also like to see the generator files move into the exercise sub directories.
(This will need support for `.meta` added in x-api or trackler or both. see:  https://github.com/exercism/x-api/issues/113)

But would mean that all the code for generating the tests for a particular exercise lives with that exercise, eg:

`exercises/slug/.meta/generator/slug_cases.rb`
`exercises/slug/.meta/generator/generic_template.tt`
`exercises/slug/.meta/generator/slug_template.tt`

(This may be a different issue, but I thought I'd add it here for now as a wish.)

**Comment by kotp** [comment]
I think `workload` has been discussed for this.  I would like to see the same terms used as well.

The `skipped` method used in `lib/hamming_cases.rb` and the related `exercises/hamming/example.tt` file is my preferred way, reducing complexity in the template file (the view).

**Comment by kotp** [comment]
Thank you @bmulvihill this is being addressed via the generator work currently done with @hilary  and previously done with @tommyschaefer and @Insti and others.
