### ISSUE TITLE
Changes to Bowling tests

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xruby#456]
We recently rewrote the test suite for Bowling. Since this track implements Bowling, please [take a look at the new canonical_data.json file](https://github.com/exercism/x-common/blob/9049dc7f748fd038b140c878c4eaa89d09b73199/exercises/bowling/canonical-data.json) and see if your track should update its implementation or tests.

The new test suite reorders tests so that students can get to green quickly. It also reduces the number of tests so that students can focus on solving the interesting edge cases.

More details on this change are available in [this issue](https://github.com/exercism/x-common/issues/409)

**Comment by kotp** [comment]
Thanks @IanWhitney.

This is a good time to write the generator for this exercise.
