### ISSUE TITLE
Triangle: Update tests.

### ISSUE THREAD

**Issue by Insti** [exercism/xruby#472]
The common triangle test data has been updated to check properties, not types: 
https://github.com/exercism/x-common/pull/424

The tests need to be updated to match these canonical tests.

The tests can be found in [`triangle_test.rb`](https://github.com/exercism/xruby/blob/master/exercises/triangle/triangle_test.rb)

But this would be a good time to write a generator see https://github.com/exercism/xruby/issues/396 for more information about generators.

**Comment by kotp** [comment]
Closed as referenced test generator PR is now in.
