### ISSUE TITLE
[Isogram] Improvements required

### ISSUE THREAD

**Issue by Insti** [exercism/xruby#475]
- [x]  1 Method should be called `isogram?`
- [x] 2 Asserts have no failure messages.
- [x] 3 The first string tested `"duplicates"` is deceptive. (update to `"no duplicates"`)
- [ ] 4 Whitespace/hypens not excluded by documentation.
- [x] 5 Test cases contain non-ascii characters 
- [x] 6 Test cases should be named for the property they are testing.
- [x] 7 Should we add a test that the argument string is not modified by the method?

Some of these things will require updating the data in x-common.
See also: https://github.com/exercism/x-common/issues/410

**Comment by Insti** [comment]
> 7 Should we add a test that the argument string is not modified by the method?

No. This is an implementation detail, it is not mentioned in the Readme and is something that can be covered during reviews.

**Comment by Insti** [comment]
> 5 Test cases contain non-ascii characters
Fixed by: https://github.com/exercism/x-common/pull/433

**Comment by Insti** [comment]
> 6 Test cases should be named for the property they are testing.

https://github.com/exercism/x-common/pull/433 also adds descriptions that can be used to generate better test names.

**Comment by Insti** [comment]
> 3 The first string tested "duplicates" is deceptive. (update to "no duplicates")

Fixed in x-common

**Comment by Insti** [comment]
> 6 Test cases should be named for the property they are testing.
Fixed by #500

**Comment by deohtee** [comment]
Hello! I just wanted to clarify the remaining three points: 
- [ ] 1. Method should be called `isogram?` 
Example: `assert Isogram.isogram?(string)` instead of the current `assert Isogram.is_isogram?(string)`

- [ ] 2. Asserts have no failure messages.
Example: `assert Isogram.is_isogram?(string), "#{some_error_message}"`

- [ ] 4. Whitespace/hypens not excluded by documentation.
Adding to the documentation that the examples may include whitespace and hyphens

**Comment by Insti** [comment]
1. Yes.
2. Yes.
4. (4?) will require a change in [x-common](https://github.com/exercism/x-common) to either: a) remove tests with hyphens/whitespace b) add something to the description about ignoring spaces and hyphens.

**Comment by Insti** [comment]
The whitespace/hyphen thing is not an xruby issue, so I think this is done!
Yay. :tada:
Thanks for your help @deohtee.

**Comment by Insti** [comment]
There is now an issue in x-common for the whitespace/hypens: https://github.com/exercism/x-common/issues/824

**Comment by deohtee** [comment]
Awesome thanks your help again! 😄
