### ISSUE TITLE
Remove rainbow gem from Gemfile

### ISSUE THREAD

**Issue by Insti** [exercism/xruby#517]
https://github.com/exercism/xruby/pull/516 added a line to the Gemfile to require a specific version of `rainbow` to workaround a bug introduced in version 2.2.0 of that gem.

Once the issue in `rainbow` gem is resolved it should be removed from the Gemfile again.

This issue has been created as a reminder to do that.

**Comment by kotp** [comment]
Thanks.  I had put it in my notifications for the gem, but this will work as well.
