### ISSUE TITLE
Non-Exercise tests in CI

### ISSUE THREAD

**Issue by tommyschaefer** [exercism/xruby#519]
Hi there!

Just opening this to get some feedback. Do you all think that non-exercise (e.g. generator) tests should be run on CI? Currently all exercise tests get run as a part of CI, but tests in the `/test` directory do not.

If they should be run on CI, do you think it would be best to add `rake test` to the Travis scripts, or should the `test` target of the Makefile be modified to run these tests?

Thank you so much for your time!

**Comment by Insti** [comment]
Yes they should.

Adding `rake test` to Travis seems like the right solution.

Longer term, I'd like to see `make` phased out in favor of `rake`.
