### ISSUE TITLE
Update README.md#Generated Test Suites section

### ISSUE THREAD

**Issue by kotp** [exercism/xruby#529]
There is room for path clarification in list.

There should also be mention of the new `bin/generate -h` command and friends.

**Comment by hilary** [comment]
@kotp do we still need this issue? We've overhauled this section of the documentation pretty thoroughly.

I'm not sure I see the need to mention `bin/generate -h`. A cli should be expected to provide `-h`.

**Comment by kotp** [comment]
In the interest of new programmers, those that are unfamiliar with the Unix tradition of --help or -h as opposed to `/?` in Windows... having a cookie to indicate where to get help is probably a good thing.

**Comment by hilary** [comment]
Discussed (in context) `bin/generate -h` in updated README in exercism/xruby#579

**Comment by Insti** [comment]
README.md now looks sufficiency updated to consider this done.
