### ISSUE TITLE
Add generator for "say"

### ISSUE THREAD

**Issue by tommyschaefer** [exercism/xruby#530]
The exercise `say` should use generated tests (#396).

Canonical data for this exercise has already been created in [exercism/x-common](https://github.com/exercism/x-common) and can be viewed [here](https://github.com/exercism/x-common/blob/master/exercises/say/canonical-data.json).

`Say` does not currently use bookkeeping, so you will need to add a version file at `exercises/say/.meta/.version` and add the following to `exercises/say/example.rb`:

```ruby
module BookKeeping
  VERSION = 1
end
```

To generate tests you will need to create a generator at `lib/say_cases.rb` and a template at `exercises/say/example.tt`.

All generators currently adhere to a common public interface, and must define the following three methods:

- `test_name` - Returns the name of the test (i.e `test_one_equals_one`)
- `workload` - Returns the main syntax for the test. This will vary depending on the test generator and its underlying implementation
- `skipped` - Returns skip syntax (i.e. `skip` or `# skip`)

The `wordy` exercise can be used as an example while building this generator:
- [Canonical Data](https://github.com/exercism/x-common/blob/master/exercises/wordy/canonical-data.json)
- [Tests](https://github.com/exercism/xruby/blob/master/exercises/wordy/wordy_test.rb)
- [Template](https://github.com/exercism/xruby/blob/master/exercises/wordy/example.tt)
- [Generator](https://github.com/exercism/xruby/blob/master/lib/wordy_cases.rb)

For additional information on generated tests, consult the [Generated Test Suites](https://github.com/exercism/xruby/blob/master/README.md#generated-test-suites) section of the README.

As always, if you get stuck, let us know and we'll be happy to help! :smile:

**Comment by definemethod** [comment]
I'm working on this now. I'm new to generated tests of this sort, so I'll probably be back with questions.

**Comment by definemethod** [comment]
Once I've built the generator, should I generate a new test for the PR?

**Comment by kotp** [comment]
Yes, that will serve as a proof that the generator is working.

**Comment by definemethod** [comment]
Ok sounds good. I've generated a new test, and then I went back and set the version for the generator to 1.
