### ISSUE TITLE
Changes to Luhn tests

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xruby#533]
We recently rewrote the test suite for the Luhn exercise. Since this track implements Luhn, please [take a look at the new canonical_data.json file](https://github.com/exercism/x-common/blob/master/exercises/luhn/canonical-data.json) and see if your track should update its implementation or tests.

Details on the test changes and the motivation can be found in [the PR](https://github.com/exercism/x-common/pull/474).

Tracking of these changes is being done at [the tracking issue](https://github.com/exercism/x-common/issues/491).

**Comment by kotp** [comment]
Now is a good time to do a generator for this exercise/test as well.

**Comment by kotp** [comment]
@morme Yes.

Look through the issues and if you see something you are interested in, let me know.  I do monitor the Exercism gitter rooms, and contacting me for Ruby in the [ruby gitter room](https://gitter.im/exercism/xruby) is a good place to do so if you do have questions specifically, or if you would like to have some help setting up and working on an issue.

If you are interested in working on this one specifically, there are two directions that this can go.  Either match up the current tests with the canonical_data file mentioned in the description above, or work on creating a generator library for this exercise specifically.

The generator is the long term preferred solution.

**Comment by morrme** [comment]
@kotp i'd like to know more about the generator option.

**Comment by kotp** [comment]
[This document](https://github.com/exercism/xruby/blob/efc7fef242a4d52dc33b8b00ee64e2a546e8689e/README.md#xruby) is a good place to start.  You can also look at the `lib/` folder to see the exercises that are already generated, and compare them for examples.

**Comment by kotp** [comment]
Thanks @hilary !!

**Comment by kotp** [comment]
@thanks @morme for considering to work on this as well.  Hopefully I have not missed your contribution.

**Comment by morrme** [comment]
@kotp this was one i fought with a little. i still want to get this workflow down, because it would be good to do it on other exercises.

**Comment by hilary** [comment]
@morrme We updated the documentation for the generators; it was a bit ... obscure :D

**Comment by morrme** [comment]
@hilary i blamed my  inexperience. good to know!

**Comment by Insti** [comment]
Definitely not your fault @morrme.
