### ISSUE TITLE
SpaceAge clarification

### ISSUE THREAD

**Issue by stevensonmt** [exercism/xruby#534]
Just did the SpaceAge exercise without looking at the test suite first.  My approach was to store conversion factors as a class constant and have a single conversion method that took the planet of interest as an arg.  The test suite assumes that each planet will have its own method.  Should this be clarified in the readme?  Or should test suite be broadened to accept more varied approaches?

**Comment by Insti** [comment]
I think the current test interface is OK, and introduces some interesting metaprogramming possibilities. Changing the test suite is not a good solution.

Adding more description of the desired interface would be possible, you would need to create the `xruby/exercises/space-age/HINTS.md` file for this and create a Pull Request. 
Let us know if you need help/advice on how to do this.

But I would suggest that the test suite forms an important part of the problem specification and you *really should* be looking at it, it's arguably more important that the README.

(I personally tend to attempt the problems by only running the tests not looking at the README until the end to make sure the tests cover everything.)

**Comment by stevensonmt** [comment]
Okay.  I usually do read the test suite before I start, but just felt like this was a simpler problem.  I'll just close this then.
