### ISSUE TITLE
Pangram refute tests aren't good

### ISSUE THREAD

**Issue by aborshenko** [exercism/xruby#544]
It seems that all the refute tests should really be assert tests. They seem to want to assert the negative.
For example 
```
def test_missing_character_x
    phrase = 'a quick movement of the enemy will jeopardize five gunboats'
    refute Pangram.pangram?(phrase), "#{phrase.inspect} is NOT a pangram"
end
```
This test fails if what is returned IS the SAME as "#{phrase.inspect} is NOT a pangram", but it should pass.

**Comment by stevensonmt** [comment]
The program does not need to return the string at all.  It should return `true` if the phrase is a pangram and `false` if it is not.  The *test*, however, will return the string on failure.

**Comment by Insti** [comment]
refute means assert NOT.

The method signature is: `refute(test, msg = nil)`

Where test is the thing to `test` and `msg` is the message to display when the test fails.

Documentation: http://docs.seattlerb.org/minitest/Minitest/Assertions.html

That said, it seems that the message needs to be rephrased so as to be more useful, as I suspect the message you were getting was:

```
'a quick movement of the enemy will jeopardize five gunboats' is NOT a pangram
```

Which doesn't show you what your output was or what the expected output is.
