### ISSUE TITLE
RailsConf 2017 role call

### ISSUE THREAD

**Issue by parkerl** [exercism/xruby#557]
Hey all,

Is anyone planning anything for RailsConf? I'm headed down and would love to meet some other maintainers and contributors. Drop a comment if you are going to be there!

Lew

**Comment by kotp** [comment]
Would love to make it, so far no such luck.

**Comment by Insti** [comment]
I will not be there, but will probably watch some of the talk livestreams.

**Comment by Insti** [comment]
How was it? Did you meet anyone who uses Exercism @parkerl ?
