### ISSUE TITLE
Linked List exercise tests for emptied list

### ISSUE THREAD

**Issue by kewlar** [exercism/xruby#562]
The tests for the [Linked List exercise](https://github.com/exercism/xruby/tree/master/exercises/linked-list) don't test if, when popping or shifting should leave the list empty, the reverse end of the list is cleared/nulled correctly. I.e. when the list is empty, then both the head and the tail ends should be empty/null.

Forgetting to do that is an easy mistake to make when implementing a doubly linked list (i.e. I made it), and the current test suite doesn't cover that yet.

## Possible Solution

Since the [instructions](https://github.com/exercism/x-common/blob/master/exercises/linked-list/description.md) specifically say that _"`pop` or `shift` will never be called on an 
empty list"_, a possible solution without defining the behaviour for error conditions could be:

```ruby
def test_pop_to_empty
  deque = Deque.new
  deque.push(10)
  assert_equal 10, deque.pop
  deque.push(20)
  assert_equal 20, deque.shift
end

def test_shift_to_empty
  deque = Deque.new
  deque.unshift(10)
  assert_equal 10, deque.shift
  deque.unshift(20)
  assert_equal 20, deque.pop
end
```

What do you think?

**Comment by Insti** [comment]
Hi @kewlar thanks for the report.
These tests look good, could you make a Pull request to add them.
Thanks.
