### ISSUE TITLE
Difference of squares: template has a single hardcoded test

### ISSUE THREAD

**Issue by hilary** [exercism/xruby#576]
## Expected Behavior
The data for the test should be in canonical data. Hard-coding it into the view is a smell.

## Possible Solution
I would vote for deleting the test.

Alternatively, several other exercises have a need for a custom section inserted after the generated tests that isn't simply not putting a test into canonical data. Once we decide how to handle those sections, we could leverage that technique to clean up this smell. But I would rather not encourage avoiding canonical data.

## Context
Other than this single test, difference of squares uses the default template. I wouldn't want to encourage customizing the template just to add additional tests without adding the data to canonical data.

**Comment by Insti** [comment]
Link to file being discussed: https://github.com/exercism/xruby/blob/master/exercises/difference-of-squares/example.tt

**Comment by Insti** [comment]
Yes delete the test.

How would you even write code that caused it to fail?

Tests all\* should be in the canonical-data.


\* exceptions apply for tricky and Ruby specific tests.

**Comment by Insti** [comment]
I was wondering why this test was added: 

Here is the commit that added the test: https://github.com/exercism/xruby/commit/22127fad27b9ae8e4466f1e68599d80ae81836b0

> Since the API calls for a `Squares` object to be instantiated with a
specific max value, it seems to be implied that the instance methods of
a given instance should have the same result on subsequent calls.
>
> While not common, I have seen more than one submission that didn't have
this property.

It is implementation specific so doesn't belong in canonical-data, maybe we do need it?

**Comment by Insti** [comment]
> maybe we do need it?

I'd argue we'd be better off changing the implementation to something more appropriate.
There's no reason why (and plenty of reasons why not) `Squares` should be an instantiable object.

**Comment by kotp** [comment]
Definitely a delete the test vote from me.

**Comment by hilary** [comment]
Sounds like we have decided to delete the test (yay!)

**Comment by Insti** [comment]
I'm changing my vote to keep the test.

 (but I think I'm outvoted.)

Remove it when the implementation change makes it redundant.

**Comment by hilary** [comment]
Ok, so what we want is to do two things:

1. change the implementation in `#workload` so it doesn't specify an instantiable object
1. remove the hardcoded test

**Comment by tommyschaefer** [comment]
> Remove it when the implementation change makes it redundant.

I'm okay with this too. It's a toss-up for me 😄

**Comment by kotp** [comment]
I prefer to not specify an instantiation giving way to freedom when it is appropriate.  I would need to investigate this further to be absolutely certain.  Still, if it is currently not causing a problem, it isn't one, and so not changing it provides a benefit in itself.

The call is left to @hilary in my opinion.
