### ISSUE TITLE
Generator: Use slug instead of exercise_name

### ISSUE THREAD

**Issue by Insti** [exercism/xruby#624]
`slug` is the canonical name for the name of an exercise.

A slug consists of `-` and lowercase `a-z`

The generator code sometimes refers to this identifier as `exercise_name` but confusion arises because it *also* refers to exercise_name as the slug with '-' replaced with '_'

Example:

slug: 'example-name'
exercise_name: 'example_name'

Proposal:

`slug` should always be the slug.
`exercise_name` should always be the (possibly underscored) exercise name.

Task:

Ensure that all slug and exercise_name references in the code are correct.

This is a low priority task, may take a while and need not happen all at once.

Edit: I'm open to alternate arguments if you disagree.

**Comment by hilary** [comment]
When you say 'possibly', are you referring to the possibility that the exercise name may be a single word? It may be a silly question, but the underscored version of a single word is just that word, so your wording is a bit confusing.

Other than that, I'm decidedly in favor of your proposal. I wasn't aware we had mixed the two terms 😭

**Comment by Insti** [comment]
If a slug has a `tr/-/_/` attempted on it becomes an `exercise_name` even if it didn't have any hyphens.

Maybe we should call it `slug_underscored` instead.
