### ISSUE TITLE
Scale generator exercise departs from actual music theory

### ISSUE THREAD

**Issue by zvkemp** [exercism/xruby#68]
I'd like to open this as a discussion before I attempt to fix it, because I'm not sure how pedantic we need to be with this.

In the 'scale generator' exercise:

- There's no universal standard for accidentals in chromatic scales. A lot of sources print ascending scales with sharps and descending with flats; fewer stipulate that the accidentals should follow the direction of the starting note's major key signature. I feel this test should accept a number of variations.
- The F# Major scale should be `%w(F# G# A# B C# D# E#)`, not `%w(F# G# A# B C# D# F)`. Similarly, Gb major has a Cb and not a B. There are no tests for these, but the given example does not generate these correctly.
- The d harmonic minor scale is `%w(D E F G A Bb C# D)`, not `%w(D E F G A Bb Db D)`. This may seem like a minor quibble (har har), but the definition of a harmonic minor scale is that the seventh note is raised one half-step, resulting in a rare case of a key signature with both sharps and flats.

So: a big issue is that this exercise becomes quite a bit more complicated to implement for the huge lumbering historical morass of music theory rules instead of a 'good enough' approach — is this worth pursuing?

**Comment by kotp** [comment]
Close due to "Good Enough"?

**Comment by fluxusfrequency** [comment]
Yeah I think we should close it.

**Comment by kotp** [comment]
:tada:
