### ISSUE TITLE
gigasecond: use times (not dates) for inputs and outputs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xruby#77]
A duration of a gigasecond should be measured in seconds, not
days.

The `gigasecond` problem has been implemented in a number of languages,
and this issue has been generated for each of these language tracks.
This may already be fixed in this track, if so, please make a note of it
and close the issue.

There has been some discussion about whether or not gigaseconds should
take daylight savings time into account, and the conclusion was "no", since
not all locations observe daylight savings time.

**Comment by kotp** [comment]
When converting to Time, 46 minutes 40 second (approximately) discrepancy.

Compared to former tests, I mean
.

**Comment by kytrinyx** [comment]
That sounds like daylight savings time. Is the Time in UTC or a local timezone?

**Comment by kotp** [comment]
Daylight savings would not be off by 46 minutes, though.  An hour, maybe, as that is what DST does, but , it sounds like minute and second leaps.  Date class handles things like that, time class, not so much, from what I understand.

**Comment by kytrinyx** [comment]
> A billion seconds, he told us, equals 31 years, 259 days, 1 hour, 46 minutes and 40 seconds.

I don't know if the `Date` tests are correct or the `Time` ones. I would have thought that `Time` accounts for these things, but I have not looked into it.

**Comment by kotp** [comment]
So it looks like I have something good to work from, thanks.  Though for one, I did get 39 seconds, so that is what got me thinking about the leap seconds that get put into place.

**Comment by kytrinyx** [comment]
Interesting. I really need to dig into all of this to get a better understanding of it. Time/Date/Timezones always makes me want to hide in a corner somewhere.

**Comment by kotp** [comment]
Yes, it is definitely not a shallow subject.  Should have a pull request for you in a matter of moments.

re: #78

**Comment by kotp** [comment]
I can't close this, but the pr #78 was merged and I assume this is closed?

**Comment by kytrinyx** [comment]
Ah, yes. Thanks!
