### ISSUE TITLE
Warning when using recent minitest (at least in bob)

### ISSUE THREAD

**Issue by NobbZ** [exercism/xruby#87]
Please see the following shell session:

```plain
$ ruby -rminitest -e "puts Minitest::VERSION"
5.5.1

$ ruby bob_test.rb
MiniTest::Unit::TestCase is now Minitest::Test. From bob_test.rb:4:in `<main>'
[...]
```

**Comment by kytrinyx** [comment]
Take a look at https://github.com/exercism/xruby/pull/71 -- I'm open to fixing this, I just want to be sure that we've not overlooked something that will make the barrier to getting started even higher for people who are new to programming.

**Comment by kytrinyx** [comment]
#71 got merged, so this should now be resolved.
